### ISSUE TITLE
[Question] Why the rewrite to C? Also, did you get Bison to work with Nim?

### ISSUE THREAD

**Issue by thomastay** [arturo-lang/arturo#1]
Hi, I come from the Nim forum. There i saw your post about integrating Bison with Nim, checked out your repo, and was surprised to find that the code is entirely rewritten in C. Out of curiosity, can I ask why? Also, did you ever manage to fix the Bison integration problems? The problems were dealing with the Nim GC garbage collecting Bison strings.

**Comment by drkameleon** [comment]
Fast-forward to September, guess what, the project has been re-re-written to Nim lol.

Now, regarding Bison, I did manage to make it work fine, although in the end, I've ended up writing my own lexer/parser using lexbase.
