### ISSUE TITLE
[Arithmetic\add & sub] doesn't work for `:color` literals

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1074]
**Describe the bug**
It has different behavior for literal and non-literal `:color` type.
Returns a `:color` value for non-literals and null for literals.

![image](https://user-images.githubusercontent.com/78623871/224855674-4c44c8da-5acc-4cb7-bff3-a8110cf84ae6.png)
![image](https://user-images.githubusercontent.com/78623871/224855722-a67645f4-2469-44d6-8f91-9a273d3668ec.png)

*Desktop (please complete the following information)* :
- OS: amd64/windows
- Version v/0.9.83 b/170

*Additional context*
Discovered on https://github.com/arturo-lang/arturo/pull/1072

**Comment by drkameleon** [comment]
I must have obviously forgotten to even test this! 

Good catch! 😉
