### ISSUE TITLE
[Arithmetic\mul] doesn't have the same behavior for literal and non-literal `:rational` & `:complex`

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1094]
**Describe the bug**
![image](https://user-images.githubusercontent.com/78623871/226074440-bca91839-d7db-45cc-8347-71374eeca425.png)

**Desktop (please complete the following information):**
 - OS: `x86_64/linux`
 - Browser Brave
 - Version `v/0.9.83`

**Additional context**
[Found on this comment](https://github.com/arturo-lang/arturo/pull/1072#issuecomment-1474435913)

**Comment by drkameleon** [comment]
Ooops! Yet another one... 🤯 

The good thing is I've been experimenting *a lot* with how to rewrite the Value operations (including what you mention) and I think I'm very, very close to a very nice solution.

Basically, you gave me a very interesting idea: the fusion/matching library.

And though I'm not going to use it per se (it's not that it adds too much overhead, it's just that it can be done in any very better and more tailor-to-our-needs way), I think it gave me enough inspiration to totally overhaul the way the Value identification works.

(I'll explain it thoroughly and technically in the PR I'm working on, which - despite not showing any progress in public - has already a ton of work and planning in it! :) )

**Comment by RickBarretto** [comment]
Alright! I'm happy to hear it!
Let's see the PR when it's done! 🤩
