### ISSUE TITLE
[Collections/first & last] better handling for infinite ranges

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#1097]
**Describe the bug**

Right now, trying to get the `last` element of an infinite range (e.g. `1..∞`) provokes a crash.

Also see: https://discord.com/channels/765519132186640445/829324913097048065/1086600060395081860

**Expected behavior**

In that case, we should be returning `infinity`.
In the case of `first (neg ∞)..10`, we should be returning *negative* infinity instead.

**Comment by RickBarretto** [comment]
The problem is [on line 979](https://github.com/arturo-lang/arturo/blob/master/src/library/Collections.nim#L979).
It's actually creating an *infinite* dynamic array (Sequence) iterating though its items, what is doing this problem.
I'll investigate more about it.

**Comment by RickBarretto** [comment]
I'll do a PR, my PC didn't blow up with some modifications that I did 😂😂😂 :

![image](https://user-images.githubusercontent.com/78623871/227011499-6d7092f1-fc7a-4051-82ba-159a24aef88b.png)
