### ISSUE TITLE
[Numbers\infinite] it should more intuitive to use, since it needs to be evaluated

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1102]
**Describe the bug**

I don't know how to describe it the best way, but I'll do my best for this Thread with some examples...
It's a strange bug found by `@krenium` on Discord.

The initial thread:

> I found something strange with how infinity interacts with switch: http://arturo-lang.io/playground?6VMal0
> - [@Krenium on Discord](https://discord.com/channels/765519132186640445/829324913097048065/1088571285367423036)

After this message, there is a lot of messages about this issue. So, I'll summarize it.

Both of the statements bellow should print the same value, but...
```red
a: ["a" 22 "z" 1 "f" 13]

print map a 'x -> x < ∞
; => false true false true false true

print map a 'x -> (x < ∞)? -> true -> false 
; => true true true true true true
```

As you can see, the second is printing it wrong.

I did more tests about it, and look what I found:
```red
x: "a"

;; switch is working well
print (x < ∞)? -> true -> false
; => false

;; Now, let's test with 'loop 🙂
a: ["a" 22 "z" 1 "f" 13]

loop a 'x 
-> print (x < ∞)? 
    -> true 
    -> false
; => false
; => true
; => false
; => true
; => false
; => true

;; BUT...
loop a 'x 
-> (x < ∞)? 
    -> print true 
    -> print false
; => true
; => true
; => true
; => true
; => true
; => true

loop a 'x 
-> switch x < ∞
    -> print true 
    -> print false
; => true
; => true
; => true
; => true
; => true
; => true

;; Now, let's see if it's a problem with iterators...
x: "a"
print (x < ∞)? -> true -> false
; => false
(x < ∞)? -> print true -> print false
; => true

;; And for some reason, 'do doesn't solve it when inside the 'switch
loop [1 ∞ 1] 'el -> 
    inspect (symbol? el)?
    -> do -> el
    -> el
; => 1 :integer
; => ∞ :symbol
; => 1 :integer
```

So, yeah, I know, `infinite` should be evaluated first, but why is it happening?
Even `switch x < ∞` isn't evaluating `∞` first.

> Side note: also, it can break even assign a variable, look

```red
a: ["a" 22 "z" 1 "f" 13]
loop a 'x 
-> (x < ∞)? 
    -> print true 
    -> print false
; => true
; => true
; => true
; => true
; => true

a: ["a" 22 "z" 1 "f" 13]
inf: ∞
loop a 'x 
-> (x < inf)? 
    -> print true 
    -> print false
; => true
; => true
; => true
; => true
; => true

;; BUT, this works fine:

a: ["a" 22 "z" 1 "f" 13]
loop a 'x 
-> print (x < ∞)? 
    -> true 
    -> false
```

But, why I think the problem is on `infinite`? Because it works fine for both, with `print` before and after the `switch`:

```red
a: ["a" 22 "z" 1 "f" 13]

loop a 'x 
-> print (string? x)? 
    -> true 
    -> false
; => false
; => true
; => false
; => true
; => false
; => true
    
loop a 'x 
-> (string? x)? 
    -> print true 
    -> print false
; => false
; => true
; => false
; => true
; => false
; => true
```

**Desktop (please complete the following information):**
 - OS: `arch: x86_64/linux @safe`
 - Browser Brave
 - Version `v/0.9.83 @ 2023-02-10T16:02:25+00:00`
 * tested on Playground

**Additional context**
- [Initial thread on Discord](https://discord.com/channels/765519132186640445/829324913097048065/1088571285367423036)

**Comment by drkameleon** [comment]
I'll have to have a very good look into this.

As I've explained in [this answer @ Discords](https://discord.com/channels/765519132186640445/829324913097048065/1088749916932804659), `∞` is just another symbol, so... it should be treated as such. It doesn't follow any special rules. 😉 

Now, that being said... I totally think the confusion stems from [an existing issue related to `switch`](https://github.com/arturo-lang/arturo/issues/1065), which - apparently - is more serious than I initially thought... 🤔

**Comment by RickBarretto** [comment]
@drkameleon, I think this issue can be closed. Doesn't?

**Comment by drkameleon** [comment]
I believe you're right.

So, closing it... and we may re-visit in the future in case it's necessary! 😉
