### ISSUE TITLE
Division/modulo between different length-based quantities not working right

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#1110]
**Describe the bug**

```red
1:m / 2:cm
; => 0
; should return 50!

1:m // 2:cm 
; => 0.5
; should return 50.0!
```

**Comment by RickBarretto** [comment]
So, for metric quantities should it return the lowest quantity?

**Comment by drkameleon** [comment]
Basically, the whole thing (operations between convertible-but-not-identical quantities) happens by converting one of them to the other one.

So, if we were to actually be able to perform `1:m / 1:cm`, I would say that is like `100:cm / 1:cm`, so that would be `100` (a simple Integer, not a Quantity, since it's the times `1:cm` "fits" into `1:m`).

The operation starts here (@ VM/values/operators):  https://github.com/arturo-lang/arturo/blob/master/src/vm/values/operators.nim#L868-L876

And for some reason (that I cannot remember), [`getFinalUnitAfterOperation`](https://github.com/arturo-lang/arturo/blob/master/src/vm/values/custom/vquantity.nim#L355-L380) must be returning `NumericQuantity` (which *is* correct, but not quite (since we also have to convert the units; as we would normally do with [`convertQuantityValue`](https://github.com/arturo-lang/arturo/blob/master/src/vm/values/operators.nim#L460-L478))

If you want to get the idea of how we Quantity operations work (especially in the case of different units), have a look into the implementation of `*` (it's quite tricky, but you must always have in mind *what* the logic is: I mean it's different to add meters... where you'd expect to get back meters, than multiplying meters we meters, where you'd get square meters, or meters with a number, where you'd get... meters again).

**Comment by RickBarretto** [comment]
I definitely couldn't solve this... I tried now, but... Mehh...

**Comment by drkameleon** [comment]
> I definitely couldn't solve this... I tried now, but... Mehh...

I'll have a look into it. My gut feeling says it's one of those cases where it might be a 2-line fix, but it's precisely this type of things that may be the most difficult ones... No worries! 😉
