### ISSUE TITLE
[Arithmetic\add] add support for `:integer` + `:quantity` in this specific order

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1129]
**Describe the bug**

```red
inspect 30:usd + 5
; 35:USD :quantity
inspect 5 + 30:usd
; >> Runtime | invalid operation add
;      error | between: :integer
;            | and: :quantity

```

**Desktop (please complete the following information):**
 - arch: `amd64/windows`
 - version : `v/0.9.83 b/331 @ 2023-03-30T15:09:55-03:00`

**Additional context**
- Found in #1130

**Comment by drkameleon** [comment]
I'm a tiny bit hesitant about this sort of operations.

Think of it like `append`.

```red
[1 2 3] ++ 4

**Comment by RickBarretto** [comment]
> I'm a tiny bit hesitant about this sort of operations.

So, isn't it a bug?

**Comment by drkameleon** [comment]
> > I'm a tiny bit hesitant about this sort of operations.
> 
> So, isn't it a bug?

Personally, I wouldn't really consider it a bug. However, we have to decide about this type of things and what makes sense and what doesn't. What I'm saying above is merely my personal opinion :)

**Comment by drkameleon** [comment]
As a rule, I would try to think in terms of an English language... if you can make sense out of the "phrase", then I guess the operation should be supported 😉

**Comment by RickBarretto** [comment]
> But, this:
> ```red
> 4 ++ [1 2 3]
> ```
> doesn't work and - IMHO - shouldn't.

I agree 100% with you.

> Should 2 * 30:usd and 30:usd * 2 both work? I would say yes. (Although I'm not sure that's the case... lol)

In this case `2 * 30:usd` returns `60:usd` what is wrong to me. IMO, `2 * 30:usd` should be different from `30:usd * 2`, the first returning an `:integer` and the second returning a `:quantity`. 

But, anyway, I don't see any problem if the operation with `:integer :quantity` (in this order) can't be supported, really. If you think it shouldn't I can remove the hidden tests to it. Because I commented some tests trying to cover this behavior.

**Comment by RickBarretto** [comment]
> As a rule, I would try to think in terms of an English-language sentence... if you can make sense out of the "phrase", then I guess the operation should be supported 😉

"I have 2 and I want to add 2 dollars" doesn't make sense to me at all. LOL! 
It should be: "I have 2 dollars and I want to add more 2 (or more 2 dollars)"... As it is now.

I comprehend your stream of thought.

But in this case, why does `mul` work and `add` don't?

**Comment by drkameleon** [comment]
> 2 * 30:usd should be different from 30:usd * 2, the first returning an :integer and the second returning a :quantity.

Interesting example...

The way I "read" the operation is like: give me 2 banknotes of e.g. 100 dollars (and that would be 200 ... dollars). So, I personally don't see a difference with the reverse operation.

Generally, I think multiplication between a number and a quantity should always return the quantity, independently of the order or what this quantity refers to.

Now, for me the absolutely trickiest part of all is when we are multiplying quantities together, e.g. cm with m, there we will have square-sth in the end... but we'll keep the unit of the "first" value.

Not easy waters to swim in, in any case (and a very daring move to include it in Arturo initially; I just thought quantities make a lot of sense, in general). I think there are a couple of programming languages totally focused on these type of tricks... so I guess we could copy a few ideas from them and how they do these things...

**Comment by drkameleon** [comment]
> It should be: "I have 2 dollars and I want to add more 2 (or more 2 dollars)"... As it is now.

To be honest, initially I had thought of not allowing that either. And to allow only 2 dollars + 2 dollars. But it just made sense, intuitively.

**Comment by drkameleon** [comment]
To sum up what I think, in words (N: number, Q: quantity):

- N + Q => error
- Q + N => Q
- Q + Q => Q

- N - Q => error
- Q - N => Q
- Q - Q => Q

- N * Q => Q
- Q * N => Q
- Q * Q => Q (caution with the units! error otherwise)

- N / Q => error
- Q / N => Q
- Q / Q => Q/N (depending on the units: dividing m with m, would return a number. but dividing m2 by m, would return meters!)

**Comment by drkameleon** [comment]
> But, anyway, is there a way to explain this better to users? Maybe adding this tricks into documentation/usage.

Providing example is always a good idea.

Now that you're saying it, I think Quantities are close to not-documented at all (not even the units supported!!) and we obviously should! (in the main Language documentation page)

**Comment by RickBarretto** [comment]
> To sum up what I think, in words (N: number, Q: quantity):

Thanks for the explanation! 🙂 

> and we obviously should!

Yep, I agree!

**Comment by RickBarretto** [comment]
> Have a look at this: https://frinklang.org/

Yeah, I know this language. I had read the documentation last year, and recommended to a friend of mine that does Physics, since the language was made specially for it.
