### ISSUE TITLE
[Converters\to] Revise how `:rational` works for `:floating` parameters?

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1131]
**Describe the bug**

When I try to create a rational with `1.5` and `3` as parameter, it returns me a `0/1` (the same as `1`), but as we know, the result should be `1/2`, look:

```red
$ to :rational [1.5 3]
; => 0/1
$ 1.5 // 3
; => 0.5
```

**Desktop (please complete the following information):**
- version : `v/0.9.83 b/331 @ 2023-03-30T15:09:55-03:00`
- arch    : `amd64/windows`

**Additional context**
- Found while doing #1130

**Comment by drkameleon** [comment]
Ooops! That's a total bug, doesn't look good at all!

Good that you spotted this! 😉 🚀

**Comment by drkameleon** [comment]
Looking into the whole implementation and how different languages handle Rational numbers, I start think that perhaps the best approach would be to disallow `:floating` types altogether. Generally, rational numbers are defined as numbers consisting of an integer numerator and an integer denominator.

Let me investigate a bit more... 😉

**Comment by RickBarretto** [comment]
> I start think that perhaps the best approach would be to disallow :floating types altogether. 

`:rational` is doing simplifications well, so I think we can use floating as input. But the best approach to do `:floating` -> `:rational` should multiply by 10^x and use this number as denominator.

Eg.: `1.5` should be transformed into `15/10` and just pass it to `:rational` that will do the simplification job that is working well.

Real example: `to :rational [1.5 2]`, should send `[15 20]` to `:rational` constructor.

Just an idea, well you know what fits better.

**Comment by drkameleon** [comment]
> > I start think that perhaps the best approach would be to disallow :floating types altogether.
> 
> `:rational` is doing simplifications well, so I think we can use floating as input. But the best approach to do `:floating` -> `:rational` should multiply by 10^x and use this number as denominator.
> 
> Eg.: `1.5` should be transformed into `15/10` and just pass it to `:rational` that will do the simplification job that is working well.
> 
> Real example: `to :rational [1.5 2]`, should send `[15 20]` to `:rational` constructor.
> 
> Just an idea, well you know what fits better.
> 
> But, as you said, `1.5/2` for instance doesn't makes sense at all.

I guess I'll have to brush up my math skills about rational numbers and their `:floating` equivalent! Oh my, oh my... lol

**Comment by RickBarretto** [comment]
> I guess I'll have to brush up my math skills about rational numbers and their :floatingequivalent! Oh my, oh my... lol

Is there a way to get the amount of digits after the point?

**Comment by drkameleon** [comment]
If you're willing to give it a try, you're more than welcome to...

What I mean:

I'm totally open to have Rational supporting creation via `to :rational` and one or two `:floating` point values (instead of 2 :integer values), the point is to find a valid way to convert them to a valid, perfect (and unique) Rational 😉

**Comment by RickBarretto** [comment]
Yeah, I agree with you.
This may be the best approach.

**Comment by RickBarretto** [comment]
> If you're willing to give it a try, you're more than welcome to...

All right! I will be more than happy with this!

**Comment by drkameleon** [comment]
Awesome! 😉 

FYI...

The main code for Rational-related transformations is here: https://github.com/arturo-lang/arturo/blob/master/src/vm/values/custom/vrational.nim#L67


For example `toRational` takes a `:floating` and can return a Rational. So, our scenario of supporting something like `to :rational [1.34 2.45]` could be as simple as converting the floating-point numbers via `toRational` to... Rational numbers and just combining the two to form a new one?

I don't know... Feel free to go about it as you consider best and I'll help in any way I can! 😉

**Comment by RickBarretto** [comment]
- @drkameleon, wasn't it fix at #1176?
- I'm saying it based on this [comment][comment]. Or will it be added at the upcoming #1165? 

[comment]: https://github.com/arturo-lang/arturo/pull/1176#issuecomment-1527152435

**Comment by drkameleon** [comment]
Well, I guess what happened is: the PR in question *was* merged but not into the master branch; it was actually merged into the branch/PR I'm currently working on, so I believe this issue will be closed when the PR that contains the changed is finally merged into the master branch 😉

**Comment by RickBarretto** [comment]
Alright! :wink:
