### ISSUE TITLE
Pre-built binary fails to run on Windows

### ISSUE THREAD

**Issue by vtereshkov** [arturo-lang/arturo#1166]
`libmpfr-6.dll` and `libwinpthread-1.dll` are missing.

**Comment by drkameleon** [comment]
@vtereshkov Hi and... welcome! 😄 

Can you please let me know which archive you have downloaded? Or how you built Arturo?

The issue you mentioned has - hopefully - been fixed by now, but perhaps there is a pending issue with some of the package.

Just let me know and I'll find a solution for you ASAP! 😉

**Comment by vtereshkov** [comment]
@drkameleon It's `arturo-0.9.83-full-x86_64-windows.zip` from https://arturo-lang.io/#download

**Comment by RickBarretto** [comment]
Strange... I downloaded it now to test and it's working in my machine...
But, there is no `libmpfr-6.dll` and `libwinpthread-1.dll` as you said.

Are they the same version?

```red
# version : v/0.9.83 @ 2023-02-10T16:05:36-03:00
# arch    : amd64/windows
```

![image](https://user-images.githubusercontent.com/78623871/233646551-dadf0380-ae85-4d70-9416-b8d31c9cfbcd.png)

**Comment by vtereshkov** [comment]
@RickBarretto It may just mean that you have both libraries in the default folder of your MSYS (?) installation.

**Comment by RickBarretto** [comment]
> @RickBarretto It may just mean that you have both libraries in the default folder of your MSYS (?) installation.

Yeah, you're right! Thanks for that! 😉
I got the same error masking my global path with `PATH=""`

```
$ PATH=""
$ ./arturo.exe
D:/Users/**/Documents/sandbox/art/arturo-full-x86_64-windows-latest/arturo.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

Let me see how to solve this!

**Comment by RickBarretto** [comment]
All right! Tested with masked path:

Try this into your Arturo's folder

```
curl -L https://arturo-lang.s3.amazonaws.com/libgcc_s_seh-1.dll -o libgcc_s_seh-1.dll
curl -L https://arturo-lang.s3.amazonaws.com/libwinpthread-1.dll -o libwinpthread-1.dll
curl -L https://arturo-lang.s3.amazonaws.com/libmpfr-6.dll -o libmpfr-6.dll
```

Well, it was fixed in CI, but it looks be broken for these release. Sorry for the inconvenience...
You can see these commands from [new CI's builds][new-build], but probably this release [was built using the oldest one][old-build]...

## My test:

```bash
$ curl -L https://arturo-lang.s3.amazonaws.com/libmpfr-6.dll -o libmpfr-6.dll
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2675k  100 2675k    0     0   526k      0  0:00:05  0:00:05 --:--:--  671k
$ curl -L https://arturo-lang.s3.amazonaws.com/libwinpthread-1.dll -o libwinpthread-1.dll
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 90596  100 90596    0     0  35612      0  0:00:02  0:00:02 --:--:-- 35667
$ curl -L https://arturo-lang.s3.amazonaws.com/libgcc_s_seh-1.dll -o libgcc_s_seh-1.dll
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  481k  100  481k    0     0   142k      0  0:00:03  0:00:03 --:--:--  143k
$ PATH=""
$ ls
bash: ls: No such file or directory
$ ./arturo.exe
Arturo
(c) 2019-2023 Yanis Zafirópulos

# version : v/0.9.83 @ 2023-02-10T16:05:36-03:00
# arch    : amd64/windows

# Type help to get a list of all available functions with a short description
# Type lookup "something" to lookup a specific function by name/description or type
# Type info 'symbol for info about a specific symbol or built-in function

# For multi-line input, just add a blank space at the end of a line
# Use TAB for auto-completion, UP for navigating history

# Launching interactive console - rock on! 🤘

$>

```

[new-build]: https://github.com/arturo-lang/arturo/blob/master/.github/workflows/windows.yml#L101-L118
[old-build]: https://github.com/arturo-lang/arturo/blob/master/.github/workflows/windows.yml#L95-L100

**Comment by drkameleon** [comment]
@vtereshkov I think that @RickBarretto's solution should work. (I guess it's one of those issues that - as I said - have already been fixed but are not part of the official builds, *yet*; that is, until the next official release).

Another idea, if you want to get the very latest version up and running (directly from the master branch) I have uploaded for you an archive, that should contain pretty much everything you need (Windows 64-bit version, full build) 😉

https://arturo-lang.s3.amazonaws.com/arturo-full-amd64-windows-master-0b82604.zip

**Comment by vtereshkov** [comment]
@drkameleon Thank you. Now working!

**Comment by drkameleon** [comment]
@vtereshkov Awesome! Glad to hear that!

Feel free to let us know in case you need anything else!

Also, you are welcome to join our [Discord server](https://discord.gg/YdVK2CB); there is quite some movement and you can get all your doubts solved even faster! 😉
