### ISSUE TITLE
[CLI] - Update does not work

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1181]
**Description**
Update arturo via cli breaks.

**To Reproduce**

```
$ arturo -u
>> Runtime | cannot perform download -> :block
     error | incorrect argument type for first parameter
           | accepts  \:string
```

**Expected behavior**
Arturo updated to the lastest version and no runtime error.

**Desktop**
 - OS: `Manjaro - linux`
 - Version `0.9.83`

**Additional context**
[This message from Discord][discord]

[discord]: https://discord.com/channels/765519132186640445/765519132186640448/1104010970633863198

**Comment by drkameleon** [comment]
Awesome! 🚀 (Not that the update is not working... lol)
