### ISSUE TITLE
[Library]: Fill missing documentation's examples

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1187]
**Description**

Look for functions that have its usage example not implemented and implement this.

A concrete function that was found in this state is `coalesce`.

**Related**

> Speaking of coalesce, there are no examples for it in the documentation.

[Krenium @ discord.com][message]

[message]: https://discord.com/channels/765519132186640445/829324913097048065/1105995742826475614

**Comment by drkameleon** [comment]
That's an interest small-script challenge... I guess it can be done automatically. Let me see... 😉

**Comment by drkameleon** [comment]
And done! 🚀 

https://github.com/arturo-lang/arturo/blob/master/tools/nodocs.art

Running the tool gives...

**Standard library functions with documentation:**
- [ ] prepend 
- [ ] infinite? 
- [ ] coalesce 
- [ ] range (❗ )
