### ISSUE TITLE
[Collections\drop & take] returns SIGSEGV for some parameters

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1190]
**Describe the bug**

> **Note**: I'm adding `take` to this issue too, because I think they are related functions... 

`drop` and `take` has some issues to be deal that returns `SIGSEVG`.
I'll care about their parameters as `collection`, the first one, and `number`, the second one.

## When `drop` fails
- When `number` is greater than `collection`'s length
  - ```red
    ; `take` implements this well, look:
    take [1 2 3] 4 ; => [1 2 3]
    drop [1 2 3] 4 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; should return `[]`
    ```
- When `number` is negative
  - ```red
    drop [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; how should we handle this?
    ```

## When `take` fails
- When `collection` is a `:range` kind and `number` is greater than `collection`'s length
  - ```red
    ; `take` implements this well for other `collection`'s kind, look:
    take [1 2 3] 4 ; => [1 2 3]
    take 1..3 4 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; should return `[1 2 3]`
    ```
- When `collection` is a `:range` kind and `number` is 0
  - ```red
    ; `take` implements this well for other `collection`'s kind, look:
    take [1 2 3] 0 ; => []
    take 1..3 0 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; should return `[]`
    ```
- When `number` is negative
  - ```red
    take [1 2 3] neg 1 ; timeout: sending signal KILL to command '/var/www/arturo-lang.io/arturo-0.9.83-safe-linux'
    ; how should we handle this?
    ```

**Desktop (please complete the following information):**
 - version: `v/0.9.83 @ 2023-02-10T16:02:25+00:00`
 - arch: `x86_64/linux @safe`

**Additional context**

- [This message by Krenium at discord.com][discord]
- [This Playground's Code][playground]

[discord]: https://discord.com/channels/765519132186640445/829324913097048065/1111078465849004103
[playground]: https://arturo-lang.io/playground/?PhXdub#terminal

**Comment by chunes3** [comment]
I think the expected behavior for

    inspect drop [1 2 3] 10

should be

    []

**Comment by RickBarretto** [comment]
@chunes3, ohh, yeah, you're right!
I didn't go through definitions, my bad!

**Comment by RickBarretto** [comment]
BTW, @drkameleon this function also breaks for negative numbers.
Should I reverse the index, just turn `y` argument into positive number or return an error?
