### ISSUE TITLE
Error when building on macOS

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#1237]
**Describe the bug**

The error appeared after I had to re-install macOS (so, it *must* have something to do with my own setup), but the message still seems of value... and I guess others may be having the same problem:

**To Reproduce**

`./build.nims install`

gives:

```
error: call to undeclared function 'generateDefaultMainMenu'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        generateDefaultMainMenu();
        ^
1 error generated.
Error: execution of an external compiler program 'clang -c  -w -ferror-limit=3 -DNDEBUG -fvisibility=hidden -I"/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras/mimalloc/include" -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -DWEBVIEW_COCOA=1 -O3   -I/Users/drkameleon/.choosenim/toolchains/nim-1.6.12/lib -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src/extras -I/Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/src -o /Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/.cache/@mhelpers@swebviews.nim.c.o /Users/drkameleon/Documents/Code/OpenSource/arturo-lang/arturo/.cache/@mhelpers@swebviews.nim.c' failed with exit code: 1
```

**Screenshots**

<img width="1007" alt="Screenshot 2023-07-04 at 13 58 17" src="https://github.com/arturo-lang/arturo/assets/1265028/87bb4520-5c40-4310-bde7-9114d9cfbf7c">

**Desktop:**
 - OS: macOS Ventura (13.4.1) - Intel
 - Nim: 1.6.14

**Comment by RickBarretto** [comment]
I think I found [where it may be broken][bug]. But why is other question... 😄

Basically, `generateMainMenu` is defined **exclusively** for *MacOs*

[bug]: https://github.com/arturo-lang/arturo/blob/master/src/helpers/webviews.nim#L226-L228

**Comment by drkameleon** [comment]
> I think I found [where it may be broken](https://github.com/arturo-lang/arturo/blob/master/src/helpers/webviews.nim#L226-L228). But why is other question... 😄
> 
> Basically, `generateDefaultMainMenu` is defined **exclusively** for _MacOs_

Spot on! I haven't even found the time to look it up.

Yes, apparently it *is* macOS only...

As for the reason, I'm totally baffled. Basically, I re-installed the exact same (I think!) version of macOS I had before... Now, is the whole system exactly as it was? I wish... lol (still struggling to make it all work as it was, but I'm getting there)

**Comment by RickBarretto** [comment]
Well, I may be downloaded other Nim's version... It should break, though, since the latest update was a minor version...


Also, I may be wrong. But I think that function was never declared before. It seems like call something that never existed before. I can't sure about it because I'm on my phone right now, so I had to read it manually without Ctrl+F, and I could not find that function. 

What makes sense, we can't use a function without previous declarations since C99.

**Comment by RickBarretto** [comment]
> As for the reason, I'm totally baffled. Basically, I re-installed the exact same (I think!) version of macOS I had before... Now, is the whole system exactly as it was? I wish... lol (still struggling to make it all work as it was, but I'm getting there)


😂😂😂😂 Me after reinstalling Msys2...
That was a pain to reconfigure. 

But I don't really think it's an OS's issue.
It can be Nim or Clang, though, since you're not having invocation or environment variable issues...

**Comment by RickBarretto** [comment]
Just fixing my comment, as I had said before I couldn't have a look if `generateDefaultMainMenu` was declared before properly, but now I found, and yes it was declared.

`generateDefaultMainMenu` [comes from `menubar.m`][source] (an Objective-C file), [that is imported from][import] `menubar.nim` [to `webviews.nim`][import].

[source]: https://github.com/arturo-lang/arturo/blob/master/src/extras/menubar/menubar.m#L20-L180
[import]: https://github.com/arturo-lang/arturo/blob/master/src/helpers/webviews.nim#L20-L21

**Comment by drkameleon** [comment]
Fixed in https://github.com/arturo-lang/arturo/commit/7be1ae24b5602f73496b6ef21744ec9bb986e137 🚀
