### ISSUE TITLE
[Converters/dictionary] Missing documentation for `.raw`

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#1252]
**See also:** https://discord.com/channels/765519132186640445/829324913097048065/1136303806154547361

**Comment by Ryton** [comment]
Documentation for "chunk" exists, but it is also missing in the search bar (algolia):
![image](https://github.com/arturo-lang/arturo/assets/6223082/12d8b2ed-dd34-4e57-b8eb-7cfe36e47b3a)

https://arturo-lang.io/documentation/library/iterators/chunk/

**Comment by drkameleon** [comment]
> Documentation for "chunk" exists, but it is also missing in the search bar (algolia): ![image](https://user-images.githubusercontent.com/6223082/258109088-12d8b2ed-dd34-4e57-b8eb-7cfe36e47b3a.png)
> 
> https://arturo-lang.io/documentation/library/iterators/chunk/

Noted! :)
