### ISSUE TITLE
negative elapsed time 

### ISSUE THREAD

**Issue by retsyo** [arturo-lang/arturo#1269]
I am using [arturo-full-x86_64-windows-latest](https://arturo-lang.io/#download) on windows 10 64bits

For the following code, `et-st` should always be a positive number. However, negative numbers often appear. Why?

```rebol
f: function [N][
    st: now\second

    i: 0
    count: 0
    loop 0 .. N 'i [
        if (i % 7) = 0 [
            count: count + 1
        ]
    ]

    et: now\second
    print ["used" (et - st)  " seconds, search in 0-" N ", found " count "numbers"]
]

i: 0
loop 0 .. 9 'i [
    N: 1000000000 * (i + 1)
    f N
]

```

**Comment by RickBarretto** [comment]
This is not a bug properly, what is happening is the following: `now` returns a `:date` that is noting more than a `:dictionary` with some specific functionality.

When you write down `now\second`, you're getting the `second` part, not converting to the absolute value in seconds. So, let's say your `st` gave you a `22/03/2021 15:10:20` and `et` a `22/03/2021 15:11:10`, what you're doing with `et - st` is `10 - 20`, what will return `neg 10`.

Now, how fix that. You're basically trying to get the difference between the interval in seconds, so:

```red
st: to :date .format:"dd/MM/yyyy hh:mm:ss" "22/03/2021 15:10:20"
et: to :date .format:"dd/MM/yyyy hh:mm:ss" "22/03/2021 15:11:10"

print -> (to :integer et) - (to :integer st)
```

**Comment by RickBarretto** [comment]
@drkameleon, solved. I think this may be closed.
