### ISSUE TITLE
FYI: cannot get playground to work

### ISSUE THREAD

**Issue by OneArb** [arturo-lang/arturo#1274]
**Describe the bug**
Playground does not load any code. Left pane remains empty.

https://arturo-lang.io/playground/?example=10001th%20prime#top

**To Reproduce**
When I try to enter code:

```
x: 2
print x
```

the circle turns forever.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by drkameleon** [comment]
Just fixed - hopefully! 😉 

P.S. Can you please verify it?

**Comment by OneArb** [comment]
I works fine now.

Great site and demo by the way!

**Comment by drkameleon** [comment]
> I works fine now.
> 
> Great site and demo by the way!

Thanks! 😄 We're doing our best I guess...

Feel free to join our [Discord community ](https://discord.gg/YdVK2CB) too, if you wish - there is quite some movement and you may ask whatever you want! 😉
