### ISSUE TITLE
Public-facing testing framework

### ISSUE THREAD

**Issue by BNAndras** [arturo-lang/arturo#1285]
**Is your feature request related to a problem? Please describe.**
https://github.com/arturo-lang/arturo/blob/master/tools/tester.art is used internally to test code using `ensure`, but there's no public-facing testing framework when languages increasingly come with one either built-in or available as a module.

**Describe the solution you'd like**
I'd like to see some sort of framework available to the public using idiomatic Arturo code. The specifics aren't that important as long as the user can define and run test suites which group similar test cases and can also assign human-readable labels to individual tests. Preferably, we could run all test suites declared in a file or just some of them if we pass in test suite names. Optionally, we could add a skip flag to specific tests so they're not run until the flag is removed or we run the CLI with a run-skipped switch. In the reporting stage, the CLI should report all passing tests, all failed tests, and all skipped tests.

Similar examples might be [Elm's test](https://package.elm-lang.org/packages/elm-explorations/test/latest/), [Go's testing](https://pkg.go.dev/testing), [Racket's RackUnit](https://docs.racket-lang.org/rackunit/) or [Pyret](https://pyret.org/docs/latest/testing.html).

**Comment by BNAndras** [comment]
We can probably close this since we’re using unitt now.

**Comment by drkameleon** [comment]
> We can probably close this since we’re using unitt now.

The truth is... yes! That was opened before Unitt came into existence (and before our new package manager was up and running!)

Well spotted! 😉
