### ISSUE TITLE
Minor color bug (blue: orange)

### ISSUE THREAD

**Issue by Ryton** [arturo-lang/arturo#1351]
**Describe the bug**

**To Reproduce**
```
colorlist: [ "red" "green" "blue" "orange" "cyan" "yellow" "brown" "black" "white"]
loop colorlist 'acolor [print [color do ("#"++acolor)  to :string acolor  to :string do ("#"++acolor) ]]
```

**Expected behavior**
Blue appearing as orange :) (see screenshot, in WSL2 linux terminal

**Screenshots**
![image](https://github.com/arturo-lang/arturo/assets/6223082/e299f8e8-61a0-4380-ba44-08a46f71f73f)

**Desktop (please complete the following information):**
 - OS: WSL2, linux
 - Version 
 - # version : v/0.9.83 b/1288 @ 2023-12-02T14:46:15+01:00
# arch    : amd64/linux

**Smartphone (please complete the following information):**
 - Device: laptop
 - OS: Win 11 pro

**Additional context**
Ask if something is unclear.

**Comment by Ryton** [comment]
and by extension (but you knew that already), colors arenot showing in the windows terminal 
(if you ever revamp this)
![image](https://github.com/arturo-lang/arturo/assets/6223082/f8ed9c29-3cff-4c29-be13-2f8aa31a4157)

# version : v/0.9.83 b/1307 @ 2023-12-20T15:26:11+01:00
# arch    : amd64/windows

**Comment by Ryton** [comment]
hmm, i might stand corrected, could have to do with my VS code settings. as it does work in a direct terminal (yes, different background  color here :-).
![image](https://github.com/arturo-lang/arturo/assets/6223082/7a8080ef-6c55-4a98-b658-044bd00983a9)
=> case closed, untill further notice! (sorry)

**Comment by Ryton** [comment]
as indeed, w/o monokai classic activated, it does show up correctly in the VS code emulator. mea culpa!
![image](https://github.com/arturo-lang/arturo/assets/6223082/f32b10e4-1078-4b24-97b1-283df3774622)

**Comment by drkameleon** [comment]
That's a very interesting finding, that *must* have an explanation... I mean other than your own setting perhaps?

In any case, you reminded me that we have to have another look into the terminal-related functionality, especially with respect to colors and/or Windows. So... Thanks! 😉  🚀
