### ISSUE TITLE
[System\args]: not parsing the command line as it should

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#1448]
**Describe the bug**

This is not parsing flags and putting everything into`values`...

![image](https://github.com/arturo-lang/arturo/assets/78623871/3313bfd7-5f5e-4c1c-b0d9-cb547069c3c9)

The desired behavior should be:

```red
#[
  b: true
  c: true
  name: "Rick"
  values: []
]
```

**Desktop (please complete the following information):**
 - OS: Windows11
 - Platform: `amd64/windows`
 - Version: `v/0.9.83 b/1817`

**Comment by drkameleon** [comment]
That's totally accurate. 💯  
I don't know how this got messed up. I assure you this *was* working... Hmmm...

Let's see... 🤔
