### ISSUE TITLE
Install from source instructions don't work

### ISSUE THREAD

**Issue by ErikSchierboom** [arturo-lang/arturo#1645]
**Describe the bug**
I've tried to install from source but the install instructions don't work.

**To Reproduce**
1. Go to https://github.com/arturo-lang/arturo/wiki/Building-Arturo
2. Follow the instructions
3. Run `./build.nims install`

Then see the build arguments overview being shown, not it being installed.

**Expected behavior**
The binary is built and installed.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Sonoma

**Additional context**
By digging through the source code, turns out the right instruction is:

`./build.nims build --install`

**Comment by RickBarretto** [comment]
@ErikSchierboom , thanks for submitting this issue.
Well, I didn't even know about this page, lol.

But this is clearly outdated, so thanks a lot. I'll update this as soon as possible.

Although, if you want to compile arturo locally, you can try this by yourself:

```
$ ./build.nims --log --install
```

**Comment by RickBarretto** [comment]
Annd, Wiki Updated!

@ErikSchierboom, can you tell me if running `./build.nims --install --mode mini` works for you?

**Comment by ErikSchierboom** [comment]
Yes that works.
