### ISSUE TITLE
[Net\request] Feature Request: support :string body

### ISSUE THREAD

**Issue by nick-chandoke** [arturo-lang/arturo#1790]
`request` should support passing raw strings for `body`, thus enabling the same behavior as `curl -X POST -d a=b&c=d`—simply that the url-encoded query string is now in the body instead of the url.

I've found an api that requires this instead of multipart form data, so that's why it's occurring to me to request this feature.

**Comment by drkameleon** [comment]
Thanks! Noted and *will* be implemented! 😉

**Comment by nick-chandoke** [comment]
Yes, that's what I had in mind!

**Comment by drkameleon** [comment]
> Yes, that's what I had in mind! Thank you! (Also btw thanks for Arturo in its entirety. It's the best coding thing that I've ever seen.)

First of all, thanks for the clarification! (we'll have it implemented, by tomorrow... at most)

Also - since I have just seen your comment... needless to say: thanks A LOT. I absolutely appreciate it. And that's what keeps me going :)

Stick around - interesting things coming 🚀
