### ISSUE TITLE
Problem when exporting to bytecode and executing it

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#265]
**Describe the bug**
Bytecode export (`-c`) and execution (`-x`) feature doesn't seem to be working on Windows.

**To Reproduce**

(That's a normal run on macOS)

<img width="563" alt="Screenshot 2021-04-10 at 12 24 04" src="https://user-images.githubusercontent.com/1265028/114266717-07fea480-99f8-11eb-890e-8b1eb6c50148.png">

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by Kyllingene** [comment]
Is there an issue here? It looks like when you ran it with `-x` it produced the expected result.

**Comment by drkameleon** [comment]
> Is there an issue here? It looks like when you ran it with `-x` it produced the expected result.

That's weird.

To be honest, I haven't tested it since then. Exporting-to and running-from bytecode is still rather experimental.

Did you manage to run the above example on Windows without any issue?

If it is so, then I guess I should start thinking about closing the issue altogether. (At least, for me on macOS, it keeps working without any issue whatsoever).

**Comment by Kyllingene** [comment]
You're right, it does error out with `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`. I came across this a couple times in the REPL, but simply re-opening it fixed it there; this issue is different though.

**Comment by drkameleon** [comment]
Hmm... Thanks for letting me know.

The error above is clearly related to memory access - which, weirdly so, doesn't happen on any *nix. I'll have to look into it and see what may being going on.

**Comment by Kyllingene** [comment]
I was trying to set up a simple webserver test, and ran into the same memory error upon trying to access a route. The example code for `serve` works just fine, it seems to be something with multiline strings (considering that is the only functional difference between my program and the example program).

**Comment by drkameleon** [comment]
> I was trying to set up a simple webserver test, and ran into the same memory error upon trying to access a route. The example code for `serve` works just fine, it seems to be something with multiline strings (considering that is the only functional difference between my program and the example program).

Can you send me a concrete example to look into it?

**Comment by Kyllingene** [comment]
Upon second checking the test example again, I noticed something I missed before: the page data is encapsulated in a block. After wrapping them in one, it seems to work fine. The only problem I see here now is that attempting to route to a raw string doesn't return an error.

**Comment by drkameleon** [comment]
Let me show you a very simple working example:

```red
serve.verbose .port:18966 #[
    "/":                          [ "<h1>This is the homepage</h1>" ]
    "/about":                     [ "This is the about page"]
    "/post/(?<title>[a-z]+)":     [ 
        t: upper title
        ~"We are in post: |t|" 
    ]
]
```

By using `.verbose`, you make the `serve` command output some useful messages.

And this is what it looks like...

**Our page**

<img width="537" alt="Screenshot 2021-12-06 at 10 06 09" src="https://user-images.githubusercontent.com/1265028/144818285-4eca5899-d109-4c5f-ab30-08c19985d90c.png">

**The server (with its log)**

<img width="411" alt="Screenshot 2021-12-06 at 10 08 15" src="https://user-images.githubusercontent.com/1265028/144818428-2b1c13f8-faf4-4ef5-80a9-1bc995ec0933.png">

---

P.S. There are - obviously - many details to iron out, but the main idea as is more than evident is something along the lines of Sinatra's simplicity.

**Comment by drkameleon** [comment]
Continued in #633 :)
