### ISSUE TITLE
Difficulties with  installing Arturo

### ISSUE THREAD

**Issue by Tovim** [arturo-lang/arturo#280]
Hi,
I would like to install Arturo on my Windows 10. I have installed MinGw-64b, Nim1.4.6-64b, downloaded Atruro via
> git clone https://github.com/arturo-lang/arturo.git              OK
>cd arturo                                                                                    OK 
>./install                                         doesn't work:
'.' is not recognized as an internal or external command,
operable program or batch file                                                     install file does exists  

Please, help me.
Tovim

**Comment by drkameleon** [comment]
> Hi,
> I would like to install Arturo on my Windows 10. I have installed MinGw-64b, Nim1.4.6-64b, downloaded Atruro via
> 
> > git clone https://github.com/arturo-lang/arturo.git              OK
> > cd arturo                                                                                    OK
> > ./install                                         doesn't work:
> > '.' is not recognized as an internal or external command,
> > operable program or batch file                                                     install file does exists
> 
> Please, help me.
> Tovim

Hi!

Did you finally manage to install Arturo?

In any case, especially for Windows, I would recommend you to prefer the pre-built binaries (either the official release or one of the nightlies). It may be the "mini" version, but it's more than enough for most use cases and the fastest way to get started.

Let me know how it went ;)

**Comment by Tovim** [comment]
Well, pre-built binaries (mini) did I try.
Firstly, I was informed that the libgmp-10.dll file was missing. I have got it and put it into "arturo-mini" directory as well as into C:/windows/System32 folder.
Secondly, this didn't help because now I am getting the following message:
arturo.exe - Application error -> There was not possible to start the application (0xc000007b) correctly.
Some notes:
The libgmp-10.dll is 32-bit.
I have checked my PC with an Outbyte PC Repair.
PHM, Tovim

**Comment by drkameleon** [comment]
Can you please have a look at here: https://discord.com/channels/765519132186640445/765519132186640448/831153927767588864

The issue you mentioned seems to have been solved.

I don't have a Windows machine myself to be able to check it out right now, but the thing is... if you got one of the mini builds (>= 0.9.75), the GMP dependency shouldn't be there at all.

Which one exactly have you been trying?

**Comment by Tovim** [comment]
Hi,
what am I to seek at the Discord site? I have opened a server (Tovim's server) there.
As to Arturo,  the described errors stems from the arturo-0.9.75-Windows-mini build.
I have also downloaded a build via git clone without success as already mentioned.
Tovim

**Comment by drkameleon** [comment]
Hmm... I'll look into it and will let you know.

P.S. The Discord link I sent you was to the "official" Arturo server (https://discord.gg/YdVK2CB) You can find many related talks there (and quite related to the issue you had).
