### ISSUE TITLE
literal value use gives weird results

### ISSUE THREAD

**Issue by progamateur** [arturo-lang/arturo#286]
Os: Windows 10
Version: 20H2
System/processor type: 64 bits

Arturo version :  v/0.9.75 b/437 @ 2021-04-29T10:42:26+02:00 

self explained code example that gives weird results

    i: 9
    inc 'i
    print ["i value -> " i] 	        ; -> 10
		
    j: 9
    print ["j value -> " j ]	        ; -> 10, but should be 9

    k: 0..9
    print ["k value -> " k ]	        ; -> [0 1 2 3 4 5 6 7 8 9 10], but should be [0 1 2 3 4 5 6 7 8 9 ]
    print ["k size  -> " size k ]	; -> 11, but should be 10

notes: 
   . same weird results with playground (https://arturo-lang.io/playground/)
   . correct results for : 
           j: 8
           k: 0..8

**Comment by drkameleon** [comment]
Good catch which I should obviously had made much clearer.

When you modify a variable in-place (that is: by passing a literal, e.g.`inc 'i`), you first have to initialize it with a `new`.

Check this (@ https://arturo-lang.io/playground/?n2Ua72): 

```red
i: new 9
inc 'i
print ["i value -> " i] 	        ; -> 10
	
j: 9
print ["j value -> " j ]	        ; -> 9

k: 0..9
print ["k value -> " k ]	        ; -> [0 1 2 3 4 5 6 7 8 9 ]
print ["k size  -> " size k ]	; -> 10
```

The exact same thing would have worked flawlessly, without any need for `new`, if you only haven't decided to make in-place changes (e.g. `i: i+1`). It's just that in-place modification, actually modify a pointer... and in your case, as bizarre as it might sound, you ended up modifying... the number 9. :)
