### ISSUE TITLE
arturo options to write/read/execute bytecode are incorrect for Windows os (web page)

### ISSUE THREAD

**Issue by progamateur** [arturo-lang/arturo#311]
Os: Windows 10
Version: 20H2
System/processor type: 64 bits
Arturo version : v/0.9.75 b/451 @ 2021-04-29T23:15:47+02:00

ref. to web page: https://arturo-lang.io/documentation/command-line/

Not correct options for Windows :
=================================
To write a bytecode file from a script:
arturo -o path/to/your/script.art
This will output a path/to/your/script.art.bcode file.

To read and execute a bytecode file:
arturo -i path/to/your/script.art.bcode

Correct options for Windows
===========================
arturo -c path/to/your/script.art
This will output a path/to/your/script.art.bcode file.

To read and execute a bytecode file:
arturo -x path/to/your/script.art.bcode

**Comment by progamateur** [comment]
Issue for bytecode execution with Latest nightly @ 2021-04-29
v/0.9.75 b/454 @ 2021-04-29T23:56:26+02:00
e2.art simple script : print "Hello Arturo World"
> arturo -c e2.art
> arturo -x e2.art.bcode
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by drkameleon** [comment]
> # Not correct options for Windows :
> To write a bytecode file from a script:
> arturo -o path/to/your/script.art
> This will output a path/to/your/script.art.bcode file.
> 
> To read and execute a bytecode file:
> arturo -i path/to/your/script.art.bcode
> 
> # Correct options for Windows
> arturo -c path/to/your/script.art
> This will output a path/to/your/script.art.bcode file.
> 
> To read and execute a bytecode file:
> arturo -x path/to/your/script.art.bcode

That's a very good catch. :) And it's not even only for Windows. They are totally the same regardless of the OS, but I... obviously forgot to update the new flags to the documentation. 

I'll fix it asap (and the whole Command line section of the documentation where there are missing things like the `--no-color` flag, for no-color REPL output, especially on Windows).

**Comment by drkameleon** [comment]
> Issue for bytecode execution with Latest nightly @ 2021-04-29
> v/0.9.75 b/454 @ 2021-04-29T23:56:26+02:00
> e2.art simple script : print "Hello Arturo World"
> 
> > arturo -c e2.art
> > arturo -x e2.art.bcode
> > SIGSEGV: Illegal storage access. (Attempt to read from nil?)

That's another great catch. 😃 

The truth is the compilation from/to bytecode is a feature that I *do* want included, but I haven't worked too much on it.

Now, the weird thing with this case is that the code - unfortunately - works for me:

<img width="450" alt="Screenshot 2021-04-30 at 07 24 49" src="https://user-images.githubusercontent.com/1265028/116652392-5e229000-a985-11eb-861a-9611fabada47.png">

which means that the problem looks Windows-specific.

Let's see... I'm opening a new TODO-based issue about this to be able to keep track of pending things: https://github.com/arturo-lang/arturo/issues/312

Great job! Keep the feedback coming! 🚀

**Comment by progamateur** [comment]
. I've compiled source code (https://github.com/arturo-lang/arturo  (cf7dd86) using:
nim c --opt:size -d:NOASCIIDECODE -d:NOEXAMPLES -d:NOGMP -d:NOPARSERS -d:NOSQLITE -d:NOUNZIP -d:NOWEBVIEW -o:.\arturo .\src\arturo.nim

 . using the new "arturo.exe",  bytecote execution is ok now.

**Comment by drkameleon** [comment]
Good job. That's very interesting to know.

Btw, that makes me think it has something to do with the environment it was built on. Since the pre-built binaries are created via GitHub actions, using msys, I guess something goes wrong in between.

P.S. in order to compile directly from the repo, for the *mini* version for example, you could also do `./install mini` in the root folder of the repo, and the binary will end up in the `/bin` folder ;)

**Comment by progamateur** [comment]
But  there is a PC memory issue when executing that script:

dic: #[
a: 0
b: 0
c: 0
d: 0
e: 0
f: 0
g: 0
h: 0
i: 0
j: 0
k: 0
l: 0
m: 0
n: 0
o: 0
p: 0	 ;   ok ->  all lines after "p:0" are commented
q: 0	 ;   ok ->  used PC memory increases
r: 0	 ;   ok ->  used PC memory increases to 95%
s: 0	 ;   ok ->  used PC memory increases to 100%, execution time increases
t: 0	 ;  ko ->used  PC memory increases to 100%, execution stops and "out of memory" is displayed
;u: 0
;v: 0
;w: 0
;x: 0
;y: 0
;z: 0
]
print size dic
print dic\a

If the dictionary has too many members, memory issues occur (see  the comments)
My PC memory is (only) 4Go

**Comment by drkameleon** [comment]
Hmm... That's super weird.

Give me some time and I'll have a look into it.

**Comment by progamateur** [comment]
OK :)

**Comment by drkameleon** [comment]
P.S. Are you able to run the Iban example from Rosetta Code: https://arturo-lang.io/playground/?example=iban 

(I'm stating this as an example, since it includes a dictionary with LOTS of keys)

**Comment by progamateur** [comment]
Sorry:
E:\Downloads\arturo-master-cf7dd86\arturo-master>arturo -c iban.art & arturo -x iban.art.bcode
out of memory

**Comment by drkameleon** [comment]
> But there is a PC memory issue when executing that script:
> 
> dic: #[
> a: 0
> b: 0
> c: 0
> d: 0
> e: 0
> f: 0
> g: 0
> h: 0
> i: 0
> j: 0
> k: 0
> l: 0
> m: 0
> n: 0
> o: 0
> p: 0 ; ok -> all lines after "p:0" are commented
> q: 0 ; ok -> used PC memory increases
> r: 0 ; ok -> used PC memory increases to 95%
> s: 0 ; ok -> used PC memory increases to 100%, execution time increases
> t: 0 ; ko ->used PC memory increases to 100%, execution stops and "out of memory" is displayed
> ;u: 0
> ;v: 0
> ;w: 0
> ;x: 0
> ;y: 0
> ;z: 0
> ]
> print size dic
> print dic\a
> 
> If the dictionary has too many members, memory issues occur (see the comments)
> My PC memory is (only) 4Go

Regarding this, I just tried it and it seems to be working fine. 

<img width="349" alt="Screenshot 2021-04-30 at 16 04 49" src="https://user-images.githubusercontent.com/1265028/116706337-d3b24e80-a9cd-11eb-8005-56a1f60fafeb.png">

As a matter of fact, it's working fine even at the online playground: https://arturo-lang.io/playground/?uqKng3

Did you try running it directly like above? (I mean... with converting to bytecode and then running the bytecode)

**Comment by progamateur** [comment]
Direct execution is ok:
E:\Downloads\arturo-master-cf7dd86\arturo-master>arturo iban.art
20
0

**Comment by drkameleon** [comment]
> Direct execution is ok:
> E:\Downloads\arturo-master-cf7dd86\arturo-master>arturo iban.art
> 20
> 0

That's some great news! :)

As I said before, I wouldn't play too much with the intermediate bytecode. (The bytecode is internally compiled and executed anyway). The idea behind being able to export to and run from bytecode is something between hiding your code and speeding up execution - e.g. in case you want, in the future, to ship a more dense binary.

But for normal use, you normally wouldn't need it at all.

**Comment by progamateur** [comment]
sorry, I used  a wrong version of iban.art

For the full last nightly version, it's ok:
E:\Downloads\arturo-0.9.75-2021-04-30-Windows-full.tar\arturo-0.9.75-2021-04-30-Windows-full>arturo iban.art
GB82 WEST 1234 5698 7654 32 => valid? true
GB82 TEST 1234 5698 7654 32 => valid? false

**Comment by drkameleon** [comment]
> sorry, I used a wrong version of iban.art
> 
> For the full last nightly version, it's ok:
> E:\Downloads\arturo-0.9.75-2021-04-30-Windows-full.tar\arturo-0.9.75-2021-04-30-Windows-full>arturo iban.art
> GB82 WEST 1234 5698 7654 32 => valid? true
> GB82 TEST 1234 5698 7654 32 => valid? false

Awesome!

The only "problem" with the Iban example is that it makes calculate that would normally overflow 64-bit integer. Thus, it would absolutely need the full (GMP-enabled) version of Arturo, which supports integer operations basically as big as your RAM would support. (and, yes, all that, in the same `:integer` type, without you having to bother which one is a "simple" int, or a big int, or anything... 😉  )
