### ISSUE TITLE
The pow function does not work when both parameters are integer and the second one is negative 

### ISSUE THREAD

**Issue by progamateur** [arturo-lang/arturo#330]
Run this script on web terminal
```
prints "pow 2 neg 1.0 -> " print pow 2 neg 1.0
prints "pow 2.0 neg 1 -> " print pow 2.0 neg 1
prints "pow 2.0 neg 1.0 -> " print pow 2.0 neg 1.0
prints "pow 2 neg 1 -> " print pow 2 neg 1
```

Result:
```
pow 2 neg 1.0 -> 0.5
pow 2.0 neg 1 -> 0.5
pow 2.0 neg 1.0 -> 0.5
pow 2 neg 1 ->
```

**Comment by drkameleon** [comment]
That's an awesome catch. :)

Hadn't even noticed it. I'll fix it asap as part of the latest PR.

**Comment by drkameleon** [comment]
Current status (and written in a tiny bit more... idiomatic way 😉 )

<img width="430" alt="Screenshot 2021-05-03 at 13 31 53" src="https://user-images.githubusercontent.com/1265028/116871087-fa61c680-ac13-11eb-8705-b1de2ce2e340.png">
