### ISSUE TITLE
Some questions about the project

### ISSUE THREAD

**Issue by trenta3** [arturo-lang/arturo#380]
Hi! I stumbled upon this project when looking for a modern substitute of REBOL, and after playing a bit with arturo I find it an AWESOME project, well structured and with an incredible potential.
I also really like the fact that precompiled binaries are easily available, which makes starting off very easy.

I would like to help in developing it further (I usually have some very busy periods followed by some almost free periods so I would be helping in bursts).
I have some questions about the project and its future directions, feel free to answer whenever you have time:
1. What is your take on adding more types to the language? E.g. REBOL and RED have a moltitude of types, which include URLs, Money amounts, IPs and many other "common" types of values, which can however be built from strings.
   Did you intentionally choose to keep them down to a minimum or are you thinking about expanding them?
2. What is the short-term (e.g. 1 year) aim of the language?
3. Are green threads and/or real threads backed into the language? Is it possible currently to support some kind of parallelism / concurrency?
4. Could you mark some issues as "good first issues" so that I know where to start contributing to get more acquainted with the code base?

And then some general suggestions for possible developments, they are rather down-to-earth, but may have important implications concerning spread usage of the language:
1. Integrate a small but powerful crypto library (I'm thinking tweetNaCl https://tweetnacl.cr.yp.to/) to pave the way for more complex applications
2. Document how to use the Javascript bundle, on which I couldn't find anything. This could be a good way to see some easy-to-use applications emerge in websites.
3. Add --help flag to command line invocations to see which options are available when invoking the program.
4. Implement reading and writing a PKZIP archive (Format is documented here: https://users.cs.jmu.edu/buchhofp/forensics/formats/pkzip.html basically it has the header at the end of the file and thus we can have a file that is both an executable and a PKZIP archive) and change a little the interpreter:
   If itself (the interpreter executable) is also a PKZIP file then it extracts the found files and starts executing one of them (this allows packaging of applications written in arturo into a single file), otherwise it starts normally.
   Then it is possible to write a packager script that downloads all pre-built release executables and adds the script to all of them so that one obtains automatic packaging of an application for all the supported platforms.
5. Focus on providing basic building blocks uniformly for the various platforms: Network connection, Combinator Parsing, Concurrency so that other things can be provided as abstractions on top of them, possibly using their own DSL to be more easily expressed (in the spirit of the STEPS project http://www.vpri.org/pdf/tr2007008_steps.pdf)

Thank you very much in advance!

**Comment by drkameleon** [comment]
@trenta3 Hi, welcome to the community! (And apologies for my super-delayed reply...)

Arturo is a love-child of mine and I'm glad that you find it interesting. It's really - really - appreciated :)

Since I'm seemingly like you - with very busy periods (like this one), and with bursts of open-source creativity - give me some time and I'll go through your points one-by-one.

I already appreciate your interest in the project. In the meantime, feel free to comment/ask anything!

Have a great day! :)

**Comment by hostilefork** [comment]
@trenta3 -- Not to spam Arturo's threads, but I was checking in on the repo here to see how it was going, and noticed your comment.  It seems Ren-C is very applicable to your interests...so I thought I'd poke in and invite you to [forum.rebol.info](https://forum.rebol.info)

(There's actually an [Arturo thread there, as well.](https://forum.rebol.info/t/arturo-rebol-inspired-language/1370)...and I'd also want to bring recent developments to @drkameleon's attention as well, as time permits.)

> Focus on providing basic building blocks uniformly for the various platforms: Network connection, Combinator Parsing, Concurrency

Ren-C now is [now doing combinator-based parsing](https://forum.rebol.info/t/introducing-uparse-the-hackable-usermode-parse/1529), and for anyone who likes historical Rebol PARSE...you'll love this.  It's all usermode at the moment, so slow right now.  But before optimizing/nativizing it, trying to beef up the testing surface and catch design issues.

The tests are a good way to look around at the abilities:

https://github.com/metaeducation/ren-c/tree/master/tests/parse

> Document how to use the Javascript bundle,

http://hostilefork.com/media/shared/replpad-js/
https://2019.reb4.me/talks

> Implement reading and writing a PKZIP archive

https://github.com/metaeducation/ren-c/blob/master/scripts/unzip.reb

> Integrate a small but powerful crypto library

We use mbedTLS, which I've been happy with.

https://github.com/metaeducation/ren-c/tree/master/extensions/crypt

Tons more on the forum, so please join and ask anything you like there.  I am devoting myself *more* than full time to Ren-C at this point...so it's coming along about as fast as any gigantic effort mostly written by one person can go.  :-/

**Comment by trenta3** [comment]
Thanks a lot for pointing the project out to me, I will see it in a couple
of days and reply back to you. I remember seeing it already on GitHub, but
it was lacking  clear instructions to compile it and needed dependencies,
as well as a little tour of the code and some basic examples to get started.

I have an initial question about Ren-C however which I find relevant
generally for REBOL-inspired languages?
Why did you choose C for development and not a more versatile language?
Doesn't using C bloat your codebase, slow down development and makes code
more difficult to understand?
What is your take on this and/or did you consider using other programming
languages?

Il dom 12 set 2021, 18:44 Hostile Fork ***@***.***> ha
scritto:

**Comment by hostilefork** [comment]
> Why did you choose C for development and not a more versatile language?
> Doesn't using C bloat your codebase, slow down development and makes code
> more difficult to understand?

forum.rebol.info is a better place for such questions than Arturo's issue database.  So I'll again direct you there.  The [Introductions section](https://forum.rebol.info/c/introductions/46) is a good place for first posts to announce one's interests and ask general questions.

But to answer quickly in case it is of general interest: I didn't pick it, Rebol originates from the late 90s.  I and others just followed along with what was open-sourced.  But Ren-C actually has extra instrumentation when built with C++--and it [gets more static analysis](https://forum.rebol.info/t/on-building-ren-c-with-c-compilers/1343).  This shores up some language features that would be hard to validate without a more advanced language on deck.

While languages like Nim are very cool, there are pros and cons to embracing a development subculture which isn't kept in check by standards committees and big industry players.  Standing on the shoulders of battle-hardened and time tested languages has no shortage of advantages.  You have centuries (millenia?) of man-years of tooling and hardening available.

Were I to start a new language project from scratch these days, I'd probably be giving a serious thought to Rust.  But really...if what you're trying to do is design a language...the focus should be on the language you are designing, not the language you are incidentally coding its implementation in.  If the design is right, the implementation language should be something that can change when needed...

**Comment by drkameleon** [comment]
Just to... chime in as well: Arturo is anything but dead. It's just that I have had to work on a different - non-open source - project for some time and it proved to be more complicated than I initially thought.

As a matter of fact, what has happened is that Arturo has become more mature and even used in a 100% production environment. If you want to have a look at the project, it's https://deleahora.com (yes, part of it has been created thanks to Arturo backstage code :) ).

Re: Arturo itself, I will very soon start updating the codebase + documentation. So, all input/feedback/contributions/etc are more than welcome! 🚀
