### ISSUE TITLE
 Error: 'deduplicate' can have side effects

### ISSUE THREAD

**Issue by retsyo** [arturo-lang/arturo#381]
**Describe the bug**
something wrong happend when try to compile arturo

**To Reproduce**
$ cd /d/tmp/arturo-master/
$ nim c -d:release src/arturo.nim
E:\msys64\home\USER\_nim\nim\lib\impure\db_sqlite.nim(184, 1) Warning: Circular dependency detected. `codeReordering` pragma may not be able to reorder some nodes properly [User]
D:\tmp\arturo-master\src\extras\bignum.nim(1148, 27) Warning: use `char` or `uint8` instead; cuchar is deprecated [Deprecated]
D:\tmp\arturo-master\src\extras\bignum.nim(1150, 27) Warning: use `char` or `uint8` instead; cuchar is deprecated [Deprecated]
D:\tmp\arturo-master\src\extras\bignum.nim(1233, 39) Warning: use `char` or `uint8` instead; cuchar is deprecated [Deprecated]
D:\tmp\arturo-master\src\extras\bignum.nim(1235, 46) Warning: use `char` or `uint8` instead; cuchar is deprecated [Deprecated]
D:\tmp\arturo-master\src\extras\bignum.nim(1572, 29) Warning: implicit conversion to 'cstring' from a non-const location: result; this will become a compile time error in the future [CStringConv]
D:\tmp\arturo-master\src\vm\env.nim(13, 12) Warning: imported and not used: 'parseopt' [UnusedImport]
D:\tmp\arturo-master\src\vm\env.nim(13, 22) Warning: imported and not used: 'sequtils' [UnusedImport]
D:\tmp\arturo-master\src\vm\env.nim(13, 32) Warning: imported and not used: 'sugar' [UnusedImport]
D:\tmp\arturo-master\src\library\Collections.nim(1357, 13) template/generic instantiation of `builtin` from here
D:\tmp\arturo-master\src\library\Collections.nim(1383, 64) template/generic instantiation of `deduplicate` from here
E:\msys64\home\USER\_nim\nim\lib\pure\collections\sequtils.nim(185, 6) Error: 'deduplicate' can have side effects
> E:\msys64\home\USER\_nim\nim\lib\pure\collections\sequtils.nim(206, 17) Hint: 'deduplicate' calls `.sideEffect` '=='
>> D:\tmp\arturo-master\src\vm\values\comparison.nim(25, 6) Hint: '==' called by 'deduplicate'
> E:\msys64\home\USER\_nim\nim\lib\pure\collections\sequtils.nim(211, 22) Hint: 'deduplicate' calls `.sideEffect` 'contains'
>> D:\tmp\arturo-master\src\vm\values\comparison.nim(261, 6) Hint: 'contains' called by 'deduplicate'

**Expected behavior**
compile without problem

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits
 - MSYS2+MINGW64
 - Nim Compiler Version 1.5.1 [Windows: amd64], Compiled at 2021-09-29

**Comment by drkameleon** [comment]
@retsyo Thanks a lot for your feedback and apologies for the ultra-delayed response. It's not very typical of me, but in that case I have had to work on different, non-open source, things... so I had to take some time off the project.

Regarding the issue: What you mention is not actually an *issue*, but more like a warning/hint by the Nim compiler. I'll have to look into it, but then there are more than a couple of things in the code that I'll have to revisit.

Have you managed to play with it?

P.S. For Windows - and in general as a matter of fact - I would suggest downloading one of the pre-compiled binaries. I think they work quite out of the box :)

**Comment by drkameleon** [comment]
Hmm.... I paid more attention to it. My mistake: It *is* an error.

That's very weird.

It must have something to do with the newer Nim version, because with 1.6.0 I myself have trouble compiling the project.

Hmm... Let's see. :)

**Comment by drkameleon** [comment]
Well, well... even though with a slight delay, I have to admit that was an awesome catch.

It was due to the more recent Nim releases. Now, it has been fixed (even for the latest stable one, that is 1.6.0) 👍

**Comment by retsyo** [comment]
nice, thank you
