### ISSUE TITLE
switch to turn off terminal color

### ISSUE THREAD

**Issue by retsyo** [arturo-lang/arturo#382]
I have downloaded arturo-0.9.77-Windows-full.zip from arturo-lang.io, which works in Windows CMD. However, since Windows CMD does not handle the color, it is not easy to read. 

So I purpose to add a swicth on compiling(I mean turn off color from arturo binary) or running( I mean tell arturo binary do not use color)   
```
D:\tmp\arturo-0.9.77-Windows-full\aguila-main>..\arturo.exe
[1;32mArturo[0m
(c) 2019-2021 Yanis Zafirópulos

[0;90m# v/0.9.77 @ 2021-10-05T09:42:59+08:00
# arch: amd64/windows[0m

[0;38;5;208m# Type [0m[1;38;5;208minfo 'symbol[0m[0;38;5;208m for info about a specific symbol or built-in function[0m
[0;38;5;208m# Type [0m[1;38;5;208mhelp[0m[0;38;5;208m to get a list of all available functions with a short description[0m

[0;38;5;208m# For multi-line input, just add a blank space at the end of a line[0m

**Comment by retsyo** [comment]
BTW, in MSYS2+MINGW64, the colored texts are displayed. However, some colors, for example gray, re still hard to read

**Comment by drkameleon** [comment]
@retsyo I totally get the issue.

That's why I have already implemented it :) (If you do an `arturo --help` you'll see what I mean).

The option/flag you were looking for is `--no-color` ;)
