### ISSUE TITLE
A description error in the documentation

### ISSUE THREAD

**Issue by xerox51** [arturo-lang/arturo#395]
**Is your feature request related to a problem? Please describe.**
I read your documentation on the arturo website. I found a little mistake in the part of in a nutshell.
At here:
; case
a: "tHis Is a stRinG"
print upper a               ; THIS IS A STRING
print lower a               ; this is a string
print capitalize a          ; tHis Is a stRinG

The output of 'print capitalize a' should be 'THis Is a stRinG'.

**Describe the solution you'd like**
You just need modify the documentation.

**Describe alternatives you've considered**
Nothing.

**Additional context**
Nothing.

**Comment by drkameleon** [comment]
Hi, and welcome!

You are totally right! 

Thanks a lot for letting me know! I will update it the very next time I update the documentation (that is: very soon :))

Thanks again!

**Comment by drkameleon** [comment]
Fixed in https://github.com/arturo-lang/arturo/commit/4c24b75cf6563b360f98a8ed091068c04dd73d4f :)

P.S. The results will be visible once I update the website,... soon.

**Comment by xerox51** [comment]
my pleasure
