### ISSUE TITLE
e constant incorrectly called epsilon

### ISSUE THREAD

**Issue by moigagoo** [arturo-lang/arturo#402]
**Describe the bug**
There's a constant in math that approximately equals 2.7. This constant is called "e." It is not called "epsilon." Epsilon is an entirety different Greek letter.

**To Reproduce**
See the docs.

**Expected behavior**
Epsilon constant should be renamed to e.

**Comment by drkameleon** [comment]
@moigagoo Hi! And thanks a lot for the comment.

I believe you have a very valid point. My main reasons, initially, for naming it like that was a) not cluttering the namespace too much, especially with an one-letter constant (but it's not an issue anymore, given the way things are handled), b) I probably got carried away by the fact that I've always heard everyone calling it "epsilon" (but, then, I *am* originally Greek, so you get the point haha)

Anyways... I think you are right. I will rename it. ;-)

Thanks! 😉 

P.S. The documentation will be updated once the new release is out.
