### ISSUE TITLE
Build errors with current Nim

### ISSUE THREAD

**Issue by AlectronikForge** [arturo-lang/arturo#41]
Just found this nice project and tried to build it with current Nim 1.2.6 on Arch Linux. Got several failures:

There are allover the project custom error types like `OverflowDefect`, `IndexDefect` etc. which the compiler does not recognize. For a quick fix I replaced them with OSError (I am new to nim and don't know better atm unfortunately)

src/vm/bytecode.nim, line 2283, proc readBytecode - `f.readStr(s, t)` appears not to exist anymore with three parameters but only two (the stream and length). Don't know how to fix that, at least in the documentation I found that specific procedure so a strange one.

src/extras/parsetoml.nim, line 1898: `undeclared identifier: deepCopy`

Do you require a certain version of Nim?

Thanks for reply!

**Comment by drkameleon** [comment]
@AlectronikForge Hi!
And thank you for your kind words! :)

Let's see what we can do.

First of all, I would try to get the latest Nim (1.4.0)

If you have installed Nim via [choosenim](https://github.com/dom96/choosenim), just do a:

```bash
choosenim update stable
```

This should update your nim installation to 1.4 and things should work. (I haven't tried it on Arch Linux, but it sure builds on Ubuntu, Windows and macOS - I believe the issues you see totally depend on the Nim version installed).

Please, let me know how it went :)

**Comment by AlectronikForge** [comment]
Yeah, now it's building flawlessly (replaced nim/nimble with choosenim).

My fault, sorry - I just guessed that AUR packages would be more or less up-to-date, given it had (c) 2020. Thanks for the hint!

**Comment by drkameleon** [comment]
Great to hear that!

I guess I'll have to make it extra clear in the README instructions. :)

P.S. Looking forward to hearing your comments - suggestions/ideas/tests/contributions of any kind are more than 100% welcome! ;-)
