### ISSUE TITLE
UI library like Jasonelle

### ISSUE THREAD

**Issue by dumblob** [arturo-lang/arturo#42]
**Is your feature request related to a problem? Please describe.**

No. Well, yes, kinda. Arturo wants to have UI, so here are some bits for the puzzle :wink:.

**Describe the solution you'd like**

Have a UI library which works top-down (more like "sculpting" - i.e. first something rough and later the details) and not bottom-up (e.g. [VID](https://github.com/red/docs/blob/master/en/vid.adoc ) dialect of Red/Rebol).

Maybe [Jasonelle]() (and subsequently Jasonette) could be a good source of inspiration.

**Describe alternatives you've considered**

Mostly-immediate-mode libraries ([Nuklear](https://github.com/Immediate-Mode-UI/Nuklear ), ImGui, [Quarks](https://github.com/Immediate-Mode-UI/Quarks ), [microui](https://github.com/rxi/microui ), ...), mostly-retained-mode libraries (99% of currently existing GUI libraries), streaming libraries ([Flyd](https://github.com/paldepind/flyd/ ), [S](https://github.com/adamhaile/S )), etc. See also [this whole thread](https://github.com/vlang/ui/issues/7#issuecomment-719636236 ).

This top-down approach shall allow for later fine-grained improvement.

**Additional context**

Shall be built around "everything live" principle (i.e. streams/reactivity). Otherwise it'll become yet another boring verbose complicated library.

For stuff Jasonelle-approach can't (or shouldn't) express I'd recommend trying SRP (synchronous reactive programming) rather then FRP (functional reactive programming) due to much lower complexity, much lower verbosity and generally simpler structure making it easier to reason about.

**Comment by drkameleon** [comment]
Well, before even reading the whole question, let me tell you: *you are absolutely reading my mind*. (Now I can keep reading what you wrote lol)
