### ISSUE TITLE
arturo 0.9.5 test failure

### ISSUE THREAD

**Issue by chenrui333** [arturo-lang/arturo#45]
👋  trying to build the latest arturo 0.9.5, but run into some issue as below:

```
==> /usr/local/Cellar/arturo/0.9.5/bin/arturo /private/tmp/arturo-test-20201106-97824-1mzoxo2/hello.art
could not load: (libmysqlclient|libmariadbclient)(|.20|.19|.18|.17|.16|.15).dylib
(compile with -d:nimDebugDlOpen for more information)
```

To me, I dont understand why it depends on mysql client stuff. Can you help me understand a bit?

Thanks,

relates to https://github.com/Homebrew/homebrew-core/pull/64264

**Comment by drkameleon** [comment]
You have a very valid point and it should have been better documented.

In the latest version, I've been experimenting with mysql (the latest version has full MySQL support), so I guess it's a missing dependency issue.

Would you mind trying `brew install mysql` before trying it again?

**Comment by chenrui333** [comment]
yeah, totally. Let me give a shot.

**Comment by chenrui333** [comment]
monitoring this github action run, https://github.com/Homebrew/homebrew-core/runs/1382085409

**Comment by drkameleon** [comment]
> monitoring this github action run, https://github.com/Homebrew/homebrew-core/runs/1382085409

Looks perfect! Thanks :)

P.s. I most definitely have to make this MySQL clear (or exclude it somehow). Did you finally get it to build?

**Comment by chenrui333** [comment]
had some syntax issue with github commit, let's see how it work snow.

**Comment by chenrui333** [comment]
yeah, it works! 🎉  Thanks @drkameleon!

**Comment by drkameleon** [comment]
> yeah, it works! 🎉 Thanks @drkameleon!

Awesome! Great to hear that. :)

Let me know how it goes :)
