### ISSUE TITLE
`\` is listed as an alias for `get` in the documentation, but it isn't

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#452]
OOB, Arturo doesn't seem to define this alias.

**Comment by drkameleon** [comment]
You are right.

Right now the documentation corresponds to the latest release. (And I believe it was valid for that one).

That's why I haven't updated for some time - until I get the new release ready (practically, after the Webview-related PR is merged 😉 )

**Comment by drkameleon** [comment]
Already addressed and fixed 😄
