### ISSUE TITLE
Crash when when using wrong number of variables with `map`

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#455]
I tried doing `map [2 3 3 4] [x y] [x + y]` to see if maybe you could iterate over the collection in jumps equal to the number of specified parameters, but that resulted in Arturo crashing rather than just informing that the attempted syntax isn't supported. 

![image](https://user-images.githubusercontent.com/281639/156888695-4b44955b-5a9b-4dae-b368-dbe08bb46b28.png)

**Comment by drkameleon** [comment]
What you mention is very interesting.

This would work fine with [`loop`](https://arturo-lang.io/documentation/library/iterators/loop/)(have a look at the 3rd example) but apparently not with `map`.

I'll implement it 😉

**Comment by drkameleon** [comment]
And... as promised, the whole thing has been implemented here: https://github.com/arturo-lang/arturo/pull/493

Basically, all of the Iterators module methods have been re-written and now support this type of thing, plus keeping track of the iteration index (with `.index`) 😄 

<img width="750" alt="Screenshot 2022-07-06 at 12 18 49" src="https://user-images.githubusercontent.com/1265028/177528839-189145fa-024b-4ff5-9c15-79d1a73bbafc.png">

So, I'm closing this issue; feel free to let me know what you think about it! 😉
