### ISSUE TITLE
Filter behavior should be adjusted

### ISSUE THREAD

**Issue by asampal** [arturo-lang/arturo#466]
Looking at the output of the filter function as below, my initial reaction was surprise:

```
$> filter [3 4 5] 'x -> x > 3
=> [3]
```

My expectation was that I would get back a collection of elements that passed the test rather than those that don't. I see that the behavior here matches the function's description, but I think the generally (e.g. JavaScript, Python, Julia, V) accepted outcome is for the condition to be an acceptance one for the resulting set.

**Comment by drkameleon** [comment]
I understand what you mean.

Basically, there are two functions right now in the library, functioning in an positive-negative fashion:

[**select**](https://arturo-lang.io/documentation/library/iterators/select/)

we have a collection and *select* (that is: keep) the items we want, based on given condition

[**filter**](https://arturo-lang.io/documentation/library/iterators/filter/)

we have a collection and *filter* (that is: reject/discard) the items we don't want, based on given condition

> **filter (v.)** pass (a liquid, gas, light, or sound) through a device to remove unwanted material

This particular case bothered me a bit in the beginning, but - if you double-think about it meaning-wise - I think the distinction is quite clear: we filter what we don't want (And yes, Ruby - I'm mentioning this as an example of language that I have used extensively, has both meaning the same thing. But I find it too confusing...) Plus, both of them have been used in sooo many places already, that renaming any of them would cause too many issues.

**Comment by asampal** [comment]
> filter (v.) pass (a liquid, gas, light, or sound) through a device to remove unwanted material

The main point of filtering, and the implication, for me at least, of this definition is to retain "the good stuff".

Smalltalk, one of the oldest languages to implement this (IIRC one of the Ruby influences), also used `select` instead of `filter` to refer to the action of retaining elements meeting the specified test. More recently, the rise in popularity of functional languages (or those which adopted functional features) led to `filter` as being the accepted name for the operation.

Anyhow, given what you said about the difficulty of refactoring to accommodate this (and the existence of `select`), I won't belabor the point. But I guarantee that people who are familiar with other languages will need "adjustment". :-)

**Comment by drkameleon** [comment]
I get your point, but as I said it could be a bit complicated right now.

Noted - and let's see how it goes in the long run. The language is still pre-1.0 (although, to be perfectly honest, I'm already using it in a very... production setting - and surprisingly it works far better than even its... creator ever imagined lol), so I guess we can afford more than a little brainstorming before things are "final". 😉 

In any case, all suggestions/ideas are welcome. We don't have to agree 100% on everything - but I definitely take every opinion into account, trust me! :)

**Comment by asampal** [comment]
I was just thinking that it might be worthwhile to have a "See also:" section shown with `info` with related functions when there is a close relationship among them. Here, for example, `filter` could point to `select`.

**Comment by drkameleon** [comment]
> I was just thinking that it might be worthwhile to have a "See also:" section shown with `info` with related functions when there is a close relationship among them. Here, for example, `filter` could point to `select` (and other iterating functional constructs).

Very valid point!

I had thought about it at some point but then totally forgot about it I guess.

I've done something similar for the website documentation (see: the related functions section) - this has been automatically generated during the documentation generation. Obviously, the result leaves a lot to be desired (it's a weird algorithm based on names/descriptions and levenshtein distances) but I guess - with some optimizations - the exact same data could come with Arturo itself (that is: included in the `info` boxes).

Hmmm... Let me see :wink:

**Comment by drkameleon** [comment]
Continued in #659 :)
