### ISSUE TITLE
Website has incorrect copyright year in footer

### ISSUE THREAD

**Issue by celtic-coder** [arturo-lang/arturo#472]
Hi Yanis (@drkameleon),

The footer on each page of the website is showing the incorrect copyright year:

![footer-year-2021](https://user-images.githubusercontent.com/11787866/159030079-beba9844-1ad4-45ae-9e7f-ed04add8722a.png)

The closing year value of "Copyright &copy; 2019-2021 Yanis Zafirópulos" is at *Line 16* in [foot.html](https://github.com/arturo-lang/arturo/blob/98c753347ef5dac37d8fa0c00c66d32aeaaff2fe/docs/website/theme/components/foot.html#L16).

As part of the template pages, *foot.html* is called from:

* *docpage.html*
* *examplepage.html*
* *function.html*
* *index.html*
* *module_index.html*
* *playground.html*

which according to [settings.art](https://github.com/arturo-lang/arturo/blob/master/docs/website/theme/settings.art) covers almost the entire website. However, I could not find *examples_index.html* referenced at [line 26](https://github.com/arturo-lang/arturo/blob/843ef53b97e7fad709a3536489e23433570c6251/docs/website/theme/settings.art#L26) of settings.art. Is this a valid template page?

Kind Regards,
Liam

**Comment by drkameleon** [comment]
Liam, Hi!

Thanks for letting me know! You're totally correct! The copyright footer is wrong.

I have been working on the documentation for the past many days and I'm still baffled by some... details (even though I *did* perform a thorough cleanup & re-organization). E.g. what you mention regarding `examples_index`, I'm afraid I have no idea what went on... I'll have to debug it.

Let's see... Hmm...

**Comment by drkameleon** [comment]
**UPDATE**

I just fixed the copyright footer, update the active compiler (for the playground) & a couple of minor issues.

And right now, I also updated the website.

Let's see what is going on with this missing... `examples_index.html` file :)

**Comment by drkameleon** [comment]
**UPDATE No.2**

OK, so I now figured it out.

This part is a leftover from some previous attempt to "categorize" the different examples @ Rosetta Code, hence that `examples_index.html` - it's not supposed to exist, nor does it mean anything is broken. :)

**Comment by drkameleon** [comment]
If you spot anything else re: the website, please let me know. (I guess I will have missed other little details here and there) 😉

**Comment by celtic-coder** [comment]
Hi Yanis (@drkameleon),

Yes, of course! If I come across anything else I will let you know, not a problem!

Kind Regards,
Liam
