### ISSUE TITLE
Missing libgmp.10.dylib on macOS

### ISSUE THREAD

**Issue by docdoctor** [arturo-lang/arturo#484]
**Describe the bug**

Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Users/mini/.arturo/bin/arturo
  Reason: tried: '/usr/local/opt/gmp/lib/libgmp.10.dylib' (no such file), '/usr/local/lib/libgmp.10.dylib' (no such file), '/usr/lib/libgmp.10.dylib' (no such file)

Fresh install of Arturo 0.9.80 using curl command. Also tried install full version from Releases.

**Desktop (please complete the following information):**
 - OS: macOS 12.4

**Comment by docdoctor** [comment]
yes, brew install gmp worked

**Comment by drkameleon** [comment]
Glad we got it working! 🚀  (Obviously, I'll have to mention this somewhere in the Getting Started section - I mean, the fact that the full version for Mac might need the GMP library installed)

Let me know in case you need *anything* else! I'm all ears! 😄

**Comment by drkameleon** [comment]
Related: #592

**Comment by drkameleon** [comment]
Updated dependencies @ https://github.com/arturo-lang/arturo/wiki/Building-Arturo
