### ISSUE TITLE
New documentaion (rename combine to couple)

### ISSUE THREAD

**Issue by guaracy** [arturo-lang/arturo#485]
`combine` was [renamed](https://github.com/arturo-lang/arturo/commit/be70c268e3ebe4f53d158a54b27c12104cb14505) to `couple` on May 9.

Arturo needs a new documentation to reflect the changes.

`combine` still in documentation
https://arturo-lang.io/documentation/library/collections/combine/

**Comment by drkameleon** [comment]
Hi!

And thanks a lot for the issue. 🚀 

I know this is the case, the `combine` command was actually renamed back then, but I generally try to follow the rule: the documentation should reflect what is in the latest official release (in that case, v0.9.80 - published in March). You know different things may change in the meantime and making a complete mess with the documentation wouldn't make much sense.

So, yes, this is pending (and I'll leave the issue open), but I think it's better to update the documentation once the next release comes out (which will be pretty soon 😉 )
