### ISSUE TITLE
Arrows operators hangs Arturo when inside a block

### ISSUE THREAD

**Issue by guaracy** [arturo-lang/arturo#500]
**Describe the bug**
Arrows operators hangs Arturo when inside a block

**To Reproduce**

Just run a script like this one

```red
print "start"
do [
  counter: 0
  setplus: function => [
      inc 'counter
  ]  
  print [ "initial=" counter]
  setplus
  print ["incremented=" counter]
  print "ok"
]
print "end"
```
results

```
start
[hangs interpreter ....]
```

**Expected behavior**
```red
print "start"
do [
  counter: 0
  setplus: function [][
      inc 'counter
  ]  
  print [ "initial=" counter]
  setplus
  print ["incremented=" counter]
  print "ok"
]
print "end"
```
results

```
start
initial= 0 
incremented= 1 
ok
```

**Desktop (please complete the following information):**
  Linux mint 64, Firefox
 - Arturo 
# v/0.9.80 b/168 @ 2022-07-07T15:49:14-03:00 
# arch: amd64/linux

**Additional context**

**Comment by drkameleon** [comment]
Thanks a lot for letting me know! 😄 

I think the thick-arrow-right operator syntactic sugar has more than a few issues - unfortunately.

Generally, I think that it works fine when used in one of the Iterators module function (e.g. `map`, `loop`, `select`, etc), but **not** when used as part of the `function` statement (or its equivalent: `$`). (Can you confirm that?)

I can imagine why this may be happening, but in any case I'll have to seriously look into it.

Let's see... 🤔

**Comment by drkameleon** [comment]
Well, I think I've finally managed to solve it! :)

<img width="371" alt="Screenshot 2022-07-08 at 14 42 25" src="https://user-images.githubusercontent.com/1265028/177994258-abc60bca-7aaa-48ea-bacc-ad04549a0c7d.png">

The fix is in the latest PR that I'm about to merge.

Please, let me know if it's working fine for you now and/or if there any other issues! 😉
