### ISSUE TITLE
[Parser] Cannot enter a number with an exponent 

### ISSUE THREAD

**Issue by guaracy** [arturo-lang/arturo#566]
**Describe the bug**
When entering a number with an exponent, if "e" is in lowercase, is treated like euler's constant. If "E" is in uppercase, runtime error with message "symbol not found".

**To Reproduce**
```
$> print 5e2
5
>> Runtime | symbol not found: e2
     error | perhaps you meant... e ?
           |                or... dec ?
           |                or... neg ?

$> print 5e-2
5
=> 0.7182818284590451

$> print [5e-2]
5 0.7182818284590451 

$> print 5E4
5
>> Runtime | symbol not found: E4
     error | perhaps you meant... or ?
           |                or... as ?
           |                or... to ?

$> print 5E-6
5
>> Runtime | symbol not found: E
     error | perhaps you meant... e ?
           |                or... a ?
           |                or... or ?
=> 6
```

**Expected behavior**
```
$> print 1e3
1000
```

**Desktop (please complete the following information):**
 - Linux Mint 20.3 x64
 - Nim 1.6.6
 - Arturo 0.9.80 b/267

**Comment by drkameleon** [comment]
Yep, you are right: Arturo currently doesn't recognize scientific notation, for now.

Btw, if you want to make sure what Arturo's parser actually sees, I'd suggest you use [`inspect`](https://arturo-lang.io/documentation/library/reflection/inspect/) with a block and anything you want inside:

<img width="218" alt="Screenshot 2022-07-25 at 10 51 54" src="https://user-images.githubusercontent.com/1265028/180737614-00df3b3a-f752-4879-a00b-8af36ded35b5.png">

Regarding scientific notation support, I must admit I had initially discarded it. But... given the [progress being made with `:quantity` values](https://github.com/arturo-lang/arturo/pull/564), where we actually parse a number-followed-by-something as... something unique (in that case, quantities), I think adding support for scientific notation wouldn't be much of a problem.

So... I'm adding it to my TODO list (unless I think of some reason why it could break other things; but, quite honestly, I doubt it...) 

Thanks for pointing it out and reminding it to me! 😉

**Comment by drkameleon** [comment]
Finally merged in main - so we have support for scientific notation! Yay! 😄
