### ISSUE TITLE
should it raise error?

### ISSUE THREAD

**Issue by retsyo** [arturo-lang/arturo#673]
I am using latest clone-and-bulit arturo on windows 10 64 bits
```
$> b: 2022

$> b.int
=> 2022

$> b.print
=> 2022
```

till now, I think this is a valid way to call function. Then
```
$> b.sin
=> 2022

$> b.sin 2*pi/4
=> 1.570796326794897

$> 2022.sin 2*pi/4
=> 1.0

$> sin 2*pi/4
=> 1.0

$> 2022.(1.0)
=> 1.0

$> 2022.1
=> 2022.1
```
so I am totally confuzed.

**Comment by drkameleon** [comment]
@retsyo Hi! 😄 

The **only** valid, canonical way to call a function is:

```
function-name function-parameter-1, function-parameter-2, etc
```

**In a few words:** to call a function, it's just the function followed by its arguments.

The `.something` syntax in Arturo is solely for [attributes or attributeLabels](https://arturo-lang.io/documentation/language/#attributes).

-----

Now, to answer your question: why is that "working" in your example?

The explanation is hopefully simple:

Arturo - internally - is stack-based machine.

When you do `F x y` and *F* is a function, then the evaluator consumes the needed number of arguments/values from the right (that's the "syntactical" part) and then - during the execution phase - each function pops its arguments from the stack.

In the REPL (running just `arturo` from the command-line), this whole thing is a tiny-bit more... lax.

### What does `b.sin` do?

Basically, it pushes one item onto the stack (**b**) and also sets an attribute (`.sin`) -- attributes are not passed to main stack, but to a distinct one: the attribute stack.

And the REPL simply prints the top-most element of the stack; that is: `b`.

### How to fix it?

Your code would normally work like this:

```red
b: 2022

print b ; to print the value

print sin b ; to print the *sin* of the value

; or...
print sin 2*pi/4 
```

-----

In Arturo's official website, you can find [loads of examples](https://arturo-lang.io/documentation/examples/) where you can get even more familiar with the syntax. An even better idea would probably be to have a look into the [In a nutshell section](https://arturo-lang.io/documentation/in-a-nutshell/), which is pretty much the whole language, by example, in an ultra-fast example read.

In any case, feel free to ask away anything else you might need; I'm all ears! 😉

**Comment by drkameleon** [comment]
Reopened by mistake.
