### ISSUE TITLE
unclip is not a good name

### ISSUE THREAD

**Issue by retsyo** [arturo-lang/arturo#682]
because after the `un`-operation, everything in the clipboard still lives in the clipboard. No former text is restored. Maybe `readclip`, `getclip` meets the real function more.

**Comment by drkameleon** [comment]
I get your point.

My only problems with `getclip` (and `readclip`):
- Normally, in Arturo, camelCase is favored (so, they would be `getClip`
- and... even then, regarding the standard library, I've avoided to use *any* compound words whatsoever for reasons of simplicity (as a matter of fact, none of the existing built-in function is of the form `doSomething`)

So, I guess we'll have to think a bit more about it...
