### ISSUE TITLE
Reduce/eliminate DLL dependencies for Windows binaries

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#858]
**Is your feature request related to a problem? Please describe.**

**See:** ➡️  https://github.com/arturo-lang/arturo/pull/856#issuecomment-1343873267

**Describe the solution you'd like**

Make sure which of the DLLs/libraries can be statically linked and proceed. We should be very careful to make sure the binaries work as before + not mess with libraries that are licensed in a way (e.g. GPL) that cannot be statically linked without the final project being of a compatible license (as is the case for Arturo).

**Comment by RickBarretto** [comment]
@drkameleon I wrote a bit about this issue [here](https://github.com/arturo-lang/arturo/pull/856#issuecomment-1344616696).
Note: I''m not a Lawyer, so It's not an advice.
