### ISSUE TITLE
no file is copied into .arturo\lib\

### ISSUE THREAD

**Issue by retsyo** [arturo-lang/arturo#860]
Now `arturo.exe` can be compiled in MSYS2/Mingw64 on windows 10 64bits, which is put under `C:\Users\MYNAME\.arturo\bin\`

A directory named `C:\Users\MYNAME\.arturo\lib\` is created too, however it is empty. Is it a bug?

**Comment by drkameleon** [comment]
Good point. No, it's not a bug. Actually, it's there as some sort of "preparation" for the upcoming package manager. That's where the external packages are supposed to go... 😉
