### ISSUE TITLE
Dates/after: not working right?

### ISSUE THREAD

**Issue by drkameleon** [arturo-lang/arturo#861]
**Describe the bug**
See: ➡️  https://discord.com/channels/765519132186640445/829324913097048065/1051564352139972729

Perhaps it's got something to do with Timezone handling in Date values?

**Comment by RickBarretto** [comment]
It's running well on stable version: 
![date manipulation test](https://user-images.githubusercontent.com/78623871/207117987-4562dcdc-97c8-4e75-92dd-1fccd2637d22.png)

My can it be some wrong commit??

**Comment by RickBarretto** [comment]
And, seeing the [latest test on master branch for Linux](https://github.com/arturo-lang/arturo/actions/runs/3664203316/jobs/6194474003#step:13:162), it's working well too.

![image](https://user-images.githubusercontent.com/78623871/207120488-9551c667-abec-49a8-a9b8-61b044186ede.png)


> Note: I used [this query to find this action](https://github.com/arturo-lang/arturo/actions?query=workflow%3ALinux+branch%3Amaster++).

It's quite strange.

**Comment by RickBarretto** [comment]
I made my search about this file history. The latest change into this function was [here](https://github.com/RickBarretto/arturo/blob/4de6a0e392a45d4389ec93d952d4000858f8b1d9/src/library/Dates.nim#L63-L71).
[Before](https://github.com/RickBarretto/arturo/blob/4de6a0e392a45d4389ec93d952d4000858f8b1d9/src/library/Dates.nim#L63-L71):
![image](https://user-images.githubusercontent.com/78623871/207124220-7b6f9c33-52c9-4b4a-b5f7-ada693cf9c97.png)
[Now](https://github.com/RickBarretto/arturo/blob/master/src/library/Dates.nim#L67-L75):
![image](https://user-images.githubusercontent.com/78623871/207124400-a6191f3c-7bf6-494e-ab70-8a7df9298328.png)

@drkameleon, Do you think it broke something here?

> Note: [ensureInPlace](https://github.com/RickBarretto/arturo/blob/master/src/library/Dates.nim#L90) was added too, but I don't think that it's the cause of this problem.

**Comment by drkameleon** [comment]
> Maybe can it be some wrong commit??

Thought about it too, but - as you have seen for yourself - I have barely touched this function's implementation lately.

My main suspicion is something to do with the timezones, perhaps even with summer vs normal times? I don't know. I guess we'll have to investigate this one a bit more... 🤔

**Comment by drkameleon** [comment]
I've tested and re-tested this error but I can honestly *not* reproduce it.

It doesn't mean that there might not be some hidden issue, but in the meantime let's consider it solved. (If there's still an issue related to this, or if somebody can actually help us reproduce it, then I'll gladly re-open it and we'll work on it).

**Comment by RickBarretto** [comment]
Do you have any idea of why?

**Comment by drkameleon** [comment]
> Do you have any idea of why?

I'm quite sure it's related to timezones.

Now, why *specifically* the OpenBSD one? 

Hmm... Not sure about this. But, it running from a VM (which I don't know much about), could have something to do with it I guess...

I'll have to investigate. My gut feeling is that not only there is a problem with that particular function (`after`), but also that there is some deep-hidden bug regarding Date values:

https://github.com/arturo-lang/arturo/blob/master/src/vm/values/value.nim#L463

**Comment by RickBarretto** [comment]
@drkameleon this issue was closed by the stale-bot.
As this was labeled as `wont-fix`, I preferred to don't open now.

Do you think this should be opened again?

**Comment by RickBarretto** [comment]
It seems everything is fine. :wink:
