### ISSUE TITLE
[Paths/module] module isn't working properly for Windows OS

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#878]
Initially we are think that were an error from [Collections/split], as related on #872

More detailed what is happening here. (The problem isn't on this library itself), look:

I created a file called `paths.art` with this code:
![image](https://user-images.githubusercontent.com/78623871/207871350-a72e568e-211f-498e-85d4-f19e086cb986.png)

Look what happens when I run it:

![image](https://user-images.githubusercontent.com/78623871/207871633-1ee14fa4-77f3-43bc-945c-098cc84d6388.png)

So, look at lines [1750](https://github.com/arturo-lang/arturo/blob/1136d74ff6685ec5b16c64021b3cf1a0dfc45fa8/src/library/Collections.nim#L1750) and [1797](https://github.com/arturo-lang/arturo/blob/1136d74ff6685ec5b16c64021b3cf1a0dfc45fa8/src/library/Collections.nim#L1797). 
Arturo is using the function `item.split(DirSep))`, `split` is a nim's standard function from `strutils.nim` module, none problem here, and `DirSep` that also is a nim's standard function comes from `osseps.nim` module, none problem here too.

But, let's see what `DirSep` returns for windows systems: 
```
  DirSep* =
    when defined(macos): ':'
    elif doslikeFileSystem or defined(vxworks): '\\'
    elif defined(RISCOS): '.'
    else: '/'
    ## The character used by the operating system to separate pathname
    ## components, for example: `'/'` for POSIX, `':'` for the classic
    ## Macintosh, and `'\\'` on Windows.
```
Yes, it'll split using a `\`. As Arturo's `module` function is returning with bot separators, it won't work. It'll separate just until user's path, and then a big string.

It's a issue related with [`module`](https://github.com/arturo-lang/arturo/blob/master/src/library/Paths.nim#L246) function.

_Originally posted by @RickBarretto in https://github.com/arturo-lang/arturo/issues/872#issuecomment-1353092615_

**Comment by RickBarretto** [comment]
I'm seeing how to solve it! 😉

**Comment by RickBarretto** [comment]
Alright, running on my local build:
![image](https://user-images.githubusercontent.com/78623871/208242022-2dd9034b-08a7-4de1-a391-31fabad18743.png)

But, I got a question. Is this error at the end a bug? It's because I called from `do` again or what?

**Comment by drkameleon** [comment]
I just saw the issue you opened.

Just one notice: since `module` was supposed to work in a way that is really not valid anymore (the whole module/package system has not been used *at all* and is to be re-designed), I wouldn't really bother with `module` per se.

What I definitely *would* fix is how `split.path` works on Windows 😉

**Comment by RickBarretto** [comment]
Hummmmmm, got it!
So, for windows, we add `\\` and `/` support. I think it should be a good approach.

**Comment by RickBarretto** [comment]
Any way, I'll push because it's just one little change to fix it.

**Comment by RickBarretto** [comment]
:rocket:
