### ISSUE TITLE
[Collections/decouple] is not working with literals

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#912]
**Describe the bug**
decouple is not working with literals. Also, it's having some incongruences, as you can see on the screenshots.

**To Reproduce**

> Note: with `;` are returns from REPL, and `;;` are my commentaries 

```arturo
a: [[1 "one"] [2 "two"] [3 "three"]]

;; With non-literal
decouple a ; => [[1 2 3] [one two three]]
a ; => [[1 one] [2 two] [3 three]]

;; With literal
decouple 'a ; => [[1 2 3] [one two three]]
;; A question about it is: It's really returning something?
a ; => [[1 one] [2 two] [3 three]]
```

**Expected behavior**
```arturo
a: [[1 "one"] [2 "two"] [3 "three"]]

;; With non-literal
decouple a ; => [[1 2 3] [one two three]]
a ; => [[1 one] [2 two] [3 three]]

;; With literal, the same behavior of non-literal
decouple 'a  ;; Does not show anything
a ; => [[1 2 3] [one two three]]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/78623871/208788015-661e7604-6492-40e9-ae42-897ab0d65e4b.png)

Also, another strange beavior:
![image](https://user-images.githubusercontent.com/78623871/208788370-a3d7e4b6-01b4-4ca8-aabd-e5bbb9f41bd2.png)

**Desktop (please complete the following information):**
- os: `amd64/windows`
- version: `v/0.9.80 b/3432`

**Additional context**
- Note: It's working well for non-literal block
- Discovered on PR #910

**Comment by drkameleon** [comment]
> ;; A question about it is: It's really returning something?

Well, it most certainly shouldn't return anything (since it's in-place, after all).

Let me see...
