### ISSUE TITLE
[Numbers/range] is not working properly?

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#913]
**Describe the bug**
Range is being quite incongruous. It's working in some places, but not for other places.

**To Reproduce**
Try run [`lib.collections.art`](https://github.com/arturo-lang/arturo/blob/60d5d0d85cfc1b6eaadbac5a8b3902daffe1df8a/tests/unittests/lib.collections.art#L224-L234) with this code inside `first`'s `do` block:

```
print first 1..10
print first 5..0
print first 0..40
```

**Expected behavior**
```
;; The return of:
; 1
; 5
; 0
``` 

But, I'm getting a:
```
>> Runtime | File: lib.collections.art
     error | Line: 330
           |
           | cannot perform first -> :integer
           | incorrect argument type for first parameter
           | accepts :string :block :range
/h/arturo ❯❯❯                                  ✘ 1 lib-collections-unittest-improvements ✱
```

**Screenshots**
- What happens when I run this code:
  ![image](https://user-images.githubusercontent.com/78623871/208791615-3db81007-496a-43f6-8759-c2dff03ccdb4.png)
  ![image](https://user-images.githubusercontent.com/78623871/208791687-403cd876-9a19-46ea-9633-d729b7d88f65.png)

- BUT, for this code:
  ![image](https://user-images.githubusercontent.com/78623871/208791771-4ff84236-dd74-46f1-af3c-f225de883a32.png)
  It's running until the end without any errors.
  ![image](https://user-images.githubusercontent.com/78623871/208791831-73d83fec-eefd-46f3-8fa6-f8b5e3d42594.png)

- AND, It's quite strange because, running on nano it's working well even inside `do` block:
  ![image](https://user-images.githubusercontent.com/78623871/208792266-c9e43644-66eb-43c2-b998-7da1bc05ffd7.png)
  > (Side-note: I used this commands after `;;`, this command writes the output on the same file you're working on.)

**Desktop (please complete the following information):**
 - os: `amd64/windows`
- version: `v/0.9.80 b/3432`

**Additional context**
- Discovered on PR #910

**Comment by RickBarretto** [comment]
On PR #910, I added this code at [this commit](https://github.com/arturo-lang/arturo/pull/910/commits/a0485e34849d2f272fd89e1b97748a9f25a5fe80)
It's not perfect, but is working.
![image](https://user-images.githubusercontent.com/78623871/208794679-1531d13b-27a8-46d5-a722-103095e38d1b.png)

**Comment by RickBarretto** [comment]
And, I'll do the same for this line here:
![image](https://user-images.githubusercontent.com/78623871/208795018-d1db23aa-26cb-4cee-91db-709b26f395a2.png)
![image](https://user-images.githubusercontent.com/78623871/208795029-e84ec94e-317d-43ce-8cfd-a22287302c75.png)

**Comment by drkameleon** [comment]
This is a weird one. I'll have to see what is going.

For now, my initial tests don't show any issue with `first` and Range values per se:

<img width="230" alt="Screenshot 2022-12-21 at 11 59 17" src="https://user-images.githubusercontent.com/1265028/208889776-a49b3edb-f797-40f0-822d-965a44ac251f.png">

**Comment by drkameleon** [comment]
Also, as a very irrelevant comment, background picture: Bled, Slovenia? lol 😛

**Comment by RickBarretto** [comment]
> Also, as a very irrelevant comment, background picture: Bled, Slovenia? lol 😛

Yep! Lake Bled in Slovenia. [Image link for Unsplash](https://unsplash.com/photos/XGDBdSQ70O0)

**Comment by RickBarretto** [comment]
If you have a look on #910, you'll see that I put every `:range` outside the `do` block.
But the strangest thing is that I tested inside `do` block using Nano, as you can see on the image I posted, and It's working well.

**Comment by drkameleon** [comment]
> > Also, as a very irrelevant comment, background picture: Bled, Slovenia? lol 😛
> 
> LOOOL 😆 Yep! Lake Bled in Slovenia. [Image link for Unsplash](https://unsplash.com/photos/XGDBdSQ70O0)

My GeoGuessr instincts... lol

**Comment by drkameleon** [comment]
> If you have a look on #910, you'll see that I put every `:range` outside the `do` block. But the strangest thing is that I tested inside `do` block using Nano, as you can see on the image I posted, and It's working well.

That looks like a serious bug... somewhere. I'm pretty sure it's not the `first` function or the Range values. Hmm... looks kind-of bad.

**Comment by drkameleon** [comment]
As thoroughly explained [here](https://github.com/arturo-lang/arturo/pull/910#issuecomment-1374447584), this is - fortunately - not a real issue.

So, I will proceed to close this one.

In case we spot any related bug, after merging [your PR with the unit-tests](https://github.com/arturo-lang/arturo/pull/910), feel free to re-open it! 😉
