### ISSUE TITLE
[Collections/insert] can't insert chars into a string

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#914]
**Describe the bug**
 I can't insert chars into a string. It works for `append` operations, for instance. And here is desirable this same behavior. 

**To Reproduce**
```
insert "helo" 2 "l"
; => hello
insert "helo" 2 `l`
; SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Expected behavior**
```
insert "helo" 2 "l"
; => hello
insert "helo" 2 `l`
; => hello
```

Without forget that it should work for literal-string too.

> Note: it's working well for literal when using :string & :string.

**Screenshots**
- :string & :char
  ![image](https://user-images.githubusercontent.com/78623871/208796412-c286d4c9-a434-4c63-9df5-69364be66fa6.png)
- :string & :string
  ![image](https://user-images.githubusercontent.com/78623871/208796430-44a9f069-68bd-4103-9d93-07cb3be3bb40.png)

**Desktop (please complete the following information):**
 - os: `amd64/windows`
- version: `v/0.9.80 b/3432`

**Additional context**
- Discovered on PR #910

**Comment by drkameleon** [comment]
Nice idea. I'll implement it! 😉
