### ISSUE TITLE
[Collections/min] is not working well for range values

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#916]
**Describe the bug**

**To Reproduce**
```
min 5..0
; => 1
;; 1?? Should be 0!

values 5..0
; => [5 4 3 2 1 0]

min.index 5..0
; => 5

min 0..5
; => 0

min.index 0..5
; => 0

values 0..5
; => [0 1 2 3 4 5]
```

It's quite similar to #915 

**Expected behavior**
```
min 5..0
; => 0
```

**Screenshots**
![image](https://user-images.githubusercontent.com/78623871/208800236-3d620ccf-d1e6-4d5f-8a9e-f8c18cdfde4f.png)

**Desktop (please complete the following information):**
- os: `amd64/windows`
- version: `v/0.9.80 b/3432`

**Additional context**
- Discovered on PR  #910

**Comment by drkameleon** [comment]
Good catch here!

Ranges are a recent additions and a couple of things around them could have underlying issues.

I'll trying solving it today! 😉
