### ISSUE TITLE
[Collections/remove] `--` is not working with `:dictionary`

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#918]
**Describe the bug**
Using `--` instead of `remove` is giving errors for `:dictionary`

> Update: It's working well for literals. :wink:

**To Reproduce**
```
user: #[name: "John" surname: "Doe"]
'user -- "Doe"
user
; => [name:John]

#[name: "John" surname: "Doe"] -- "John"
; SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Expected behavior**
```
#[name: "John" surname: "Doe"] -- "John"
; => [surname:Doe]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/78623871/208802868-c3cc4930-194a-4204-9e64-d4f20596af5f.png)
![image](https://user-images.githubusercontent.com/78623871/208884554-b1029fcb-4a51-45a7-9de2-eefe0855ecac.png)

**Desktop (please complete the following information):**
- os: `amd64/windows`
- version: `v/0.9.80 b/3432`

**Additional context**
- Discovered on PR #910

**Comment by drkameleon** [comment]
You are right.

Interestingly enough, this works:

```red
x: #[name: "John" surname: "Doe"]
remove x "John"
; => [surname:Doe]
```

**Comment by RickBarretto** [comment]
It explains a lot! Thank you!
Issue closed!
