### ISSUE TITLE
[Collections/split] is not working with string-literals

### ISSUE THREAD

**Issue by RickBarretto** [arturo-lang/arturo#927]
**Describe the bug**
`split` is not working for string-literals

**To Reproduce**
```
;; Working well
split "Arturo"
; => [A r t u r o]

a: "Arturo"
split 'a
a
; => [a]
```

**Expected behavior**
```
a: "Arturo"
split 'a
a
; => [A r t u r o]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/78623871/208920584-7a57023f-e7d7-4f31-bb6c-0fb10519044b.png)

**Desktop (please complete the following information):**
- os `amd64/windows`
- version `v/0.9.80 b/3432`

**Additional context**
- Discovered on PR #910

**Comment by drkameleon** [comment]
My inclusion is: it looks like we have *the* absolute mess with in-place literals 😆 

Let's see, let's see... 

Keep going! Very valuable work by any definition! 🚀

**Comment by RickBarretto** [comment]
> My conclusion is: it looks like we have the absolute mess with in-place literals 😆

LOOOOOOL! 😆😆😆😆😆😆 

> Keep going! Very valuable work by any definition! 🚀

Alright, thank you! 🙂
